### ISSUE TITLE
Reorganize imports not working

### ISSUE THREAD

**Issue by Limeth** [rust-lang-nursery/rustfmt#1093]
Putting `reorder_imports = true` into `rustfmt.toml` doesn't make rustfmt reorder imports.
You can try this by cloning [euclider](https://github.com/Limeth/euclider), running `cargo fmt -- --write-mode overwrite --verbose` and looking at lines with `use` in file `src/universe/d3/entity/surface.rs`.

**Comment by studoot** [comment]
I think it's intended to sort the used items in one line

```
use mod::{c, b, a};
```

becomes

```
use mod::{a, b, c};
```

Thats how I read [the source](https://github.com/rust-lang-nursery/rustfmt/blob/240dba54677c09a455d15f76f8d4f328348ebd99/src/imports.rs#L94), which I was looking at because I'd thought the same as you (that it should sort the use lines in a source file) earlier today.

**Comment by Limeth** [comment]
That explains it. I would really like to have an option to order the lines, too.

**Comment by studoot** [comment]
Yes, me too - well, this is an issue. If you re-title to "Add reordering of use statements" or something like that, then you can make it a feature request rather than a bug report?

**Comment by nrc** [comment]
That is #298. I think everything here either works or is covered by #298, so I'll close this issue. Please feel free to re-open if there something not covered.
