### ISSUE TITLE
reorder-imports panics if first line is use-statement

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#1111]
``` Rust
use foo;
```

If `reorder-imports` is `true`, rustfmt panics with

```
thread 'main' panicked at 'index 0 and/or 4294967295 in `use foo;
` do not lie on character boundary', ../src/libcore/str/mod.rs:1707
```

Most likely caused by #1104 .

**Comment by crumblingstatue** [comment]
cc @studoot

**Comment by studoot** [comment]
This and #1116 reference the same issue - it's just that @crumblingstatue built with `—release`, while @pepyakin built in debug, as far as I can tell through my testing. This means that PR #1117 will fix this issue.

I've had a look at the relevant system tests and they seem unable to detect this defect, because of the comments that indicate the formatting options used - any suggestion for what might be added to cover this boundary condition, @nrc?

**Comment by nrc** [comment]
@studoot so, you can repro this locally? And what exactly is the problem? You need a single import on the first line of the file with no comments?

**Comment by pepyakin** [comment]
@nrc about the last one: issue is not reproducing if I add comment before import. Because of this #1117 has no tests. 

All of the following tests are failing with the same issue:

```rust
use foo;
```

```rust
use quix::baz;
use foo;
```

```rust
use foo2;

fn main() { }
```

It seems it is enough to have an import on the very first line. It helps even after adding newline before import. So following code (where ⎵ — denotes newline)
```rust
⎵
use foo;
```
doesn't panics.

**Comment by studoot** [comment]
Yes, I can repro - with the files attached to #1116 extracted into a rustfmt build directory, using  `cargo run --bin rustfmt --release -- main.rs --write-mode plain`. In release mode, the arithmetic under flow detection isn't enabled, so the panic occurs when trying to resolve the character span that results.

The problem occurs because of how I'm persuading the `FmtWriter` to output an appropriate span before the use decl span - if a use declaration is first thing in a file, it has no preceding span, and its own span starts at zero. I subtract one from the start of the use decl span to get a preceding span, which is probably the wrong thing to do. @pepyakin's PR fixes the panic, but I think I need to think about a better fix for the underlying issue.

The crux of the problem re: testing is that the use decl span needs to start at zero, which precludes leading comments in the source file, so there needs to be some other way of indicating the desired configuration.

**Comment by nrc** [comment]
Hmm, it does seem there is no good way to test this. You could just use a unit test, rather than a regression test to catch it, I'd have thought.

**Comment by studoot** [comment]
I've added a PR (#1122) which adds a test case for this issue (which I've verified would catch this issue). As the PR states, it adds another route by which a test case can specify its config, which may or may not be something that you actually want, @nrc...

**Comment by crumblingstatue** [comment]
Closing, since this does not reproduce anymore.
