### ISSUE TITLE
Non-deterministic behaviour, possibly macro-related

### ISSUE THREAD

**Issue by BenjaminGill-Metaswitch** [rust-lang-nursery/rustfmt#1141]
Rustfmt 0.6. In a crate I'm working on, I have a single (known) syntax error. 

Running `rustfmt --write-mode=diff src/lib.rs`, it only picks up the error about 1/2 the time (the other 1/2 it reports no errors). 

It seems to be due to an intermediate mod.rs, with contents (comment out the macro, and the bug disappears):

``` Rust
pub mod beta;

// This seems to be responsible.
random_macro!(pub trait One: Two);
```

See https://github.com/BenjaminGill-Metaswitch/rustfmt-bug-report for my minimum repro of this behaviour.

**Comment by nrc** [comment]
Huh, the first non-determinism error, afaik.

**Comment by philipc** [comment]
The non-determinism is because we list the files in a `HashMap`, so the order depends on the random seed. The bug is that once we encounter an error parsing a macro, for all subsequent macros we think we recovered from an error, and so don't format them either.

We could cancel errors by calling  `context.parse_session.span_diagnostic.cancel(&mut e)` instead of `e.cancel()`, but that's not a complete fix because I still can't see any way to cancel the recoverable errors. So it looks like we need to create a new parse session for macros?

**Comment by nrc** [comment]
cc @jseyfried - an interesting effect of the macro parsing/error stuff here.

**Comment by callahad** [comment]
I'm also seeing nondeterminism when I try to `cargo fmt` on a project that otherwise builds just fine: https://github.com/portier/portier-broker/pull/26

What's especially fun is that it'll sometimes get into cycles where rustfmt will make a change, and then a few runs later, will make the inverse of that change. So it formats and then unformats itself.

**Comment by robertg** [comment]
+1, we use `rustup run stable cargo fmt -- --write-mode=diff` in CircleCI and are being hit by this non-determinism.

**Comment by philipc** [comment]
I think #1393 is fine as a way to make rustfmt usable at least, but it still didn't fix the bug that caused the non-deterministic order to matter, which is that we don't handle errors in macro parsing correctly.

**Comment by nrc** [comment]
@philipc so the non-determinacy is fixed, but we don't format macros which we could? IIUC, this only manifests if there is a syntax error in a macro?

**Comment by philipc** [comment]
@nrc yes
