### ISSUE TITLE
Consider increasing single_line_if_else_max_width

### ISSUE THREAD

**Issue by nivekuil** [rust-lang-nursery/rustfmt#1181]
The default 50 column limit on single-line if-else statements feels like it creates too much whitespace for simple logic. For example:

```
let dest: PathBuf = {
    let grave = graveyard.join(path.strip_prefix("/").unwrap());
    if grave.exists() { rename_grave(grave) } else { grave }
};
```

becomes

```
let dest: PathBuf = {
    let grave = graveyard.join(path.strip_prefix("/").unwrap());
    if grave.exists() {
        rename_grave(grave)
    } else {
        grave
    }
};
```

I understand the rationale behind discouraging complex one-liners, but it seems like a length restriction just encourages shorter variable names.

**Comment by nrc** [comment]
Yeah, I mostly agree and also get frustrated when we don't quite hit the length limit. However, rather than just extend the limit, I'd rather do something a little smarter, like look at the expressions in the arms (I think we already require a single expression) and allow a one-liner if there is a 'small' expression, for some definition of that.

**Comment by nrc** [comment]
Discussed at https://github.com/rust-lang-nursery/fmt-rfcs/issues/47
