### ISSUE TITLE
Unnecessary wrapping of function params when they would be exactly the maximum line length

### ISSUE THREAD

**Issue by marshallpierce** [rust-lang-nursery/rustfmt#1246]
Noticed in https://github.com/briansmith/ring/pull/385/files/91cafacb247788cfbfb272491b39dad01f0b152e#diff-ddc4e9e3097594a34ee33a52e274ecc3. 

rustfmt 0.6.3 produces:

```
pub fn expect_tag_and_get_value<'a>
    (input: &mut untrusted::Reader<'a>, tag: Tag)
     -> Result<untrusted::Input<'a>, error::Unspecified> {
```

If the params were put on the first line, it would be exactly 80 characters long, which is the maximum configured line width.

**Comment by marshallpierce** [comment]
Looks like it also happens in this case, which doesn't hit the max line length: https://github.com/briansmith/ring/pull/385/files/91cafacb247788cfbfb272491b39dad01f0b152e#diff-ddc4e9e3097594a34ee33a52e274ecc3L174

```
pub fn positive_integer<'a>
    (input: &mut untrusted::Reader<'a>) 
     -> Result<untrusted::Input<'a>, error::Unspecified> { 
```

**Comment by nrc** [comment]
This happens because we compute the space for the args assuming we will put the return type on the same line, that means we have to make room for `) `. This is hard to fix because we don't know if the return type will get a newline until after we've laid out the arguments. So this seems like it won't get fixed (which, is not too bad, since we're just being conservative, really).

**Comment by topecongiro** [comment]
Closing since this is no longer an issue with the RFC style.
