### ISSUE TITLE
rustfmt_skip yields compiler warning

### ISSUE THREAD

**Issue by shouya** [rust-lang-nursery/rustfmt#1257]
```
warning: unused attribute, #[warn(unused_attributes)] on by default
  --> src/model/ticket.rs:43:5
   |
43 |     #[rustfmt_skip]
   |     ^^^^^^^^^^^^^^
```

Is there a good way to circumvent this? Instead of adding a `#[allow(unused_attributes)]` everywhere.

**Comment by nrc** [comment]
I don't think there is currently. Long term we are thinking about how to improve the attribute experience in Rust, so we can have a better story.

You can also use the more verbose `#[cfg_attr(rustfmt, rustfmt_skip)]`, which I don't think will give you the warning and will also work in stable Rust.

Closing the issue since there is nothing actionable on the Rustfmt side.
