### ISSUE TITLE
Overaggressive line breaks on method arguments in 0.8

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/rustfmt#1380]
This is "properly formatted" for 0.7.1:

```rust
fn foo() {
    {
        {
            let creds = self.client
                .client_credentials(&self.config.auth.oauth2.id, &self.config.auth.oauth2.secret)?;
        }
    }
}
```

But 0.8 reformats it to

```rust
fn foo() {
    {
        {
            let creds = self.client
                .client_credentials(&self.config
                                         .auth
                                         .oauth2
                                         .id,
                                    &self.config
                                         .auth
                                         .oauth2
                                         .secret)?;
        }
    }
}
```

It seems fine to want to stick a newline between the two arguments, but it seems like overkill to add line breaks between every expression component.

**Comment by nrc** [comment]
This is due to the introduction of a threshold for the number of items in a chain that we will fit on one line (option: `chain_one_line_max`). With that set to something large, I get:

```
fn foo() {
    {
        {
            let creds = self_client.client_credentials(&self.config.auth.oauth2.id,
                                                       &self.config.auth.oauth2.secret);
        }
    }
}
```

I feel like for paths made only of fields the limit of 4 is maybe too small, but it works quite well when some elements are methods. Perhaps a char limit rather than a count limit would be better?

**Comment by sfackler** [comment]
I think a char limit would make more sense than a path count limit, yeah.
