### ISSUE TITLE
Poor formatting with method chains and '?' operator

### ISSUE THREAD

**Issue by edmccard** [rust-lang-nursery/rustfmt#1389]
Using rustfmt 0.8.0, I write this:

    let names = String::from_utf8(names)?.split('|').map(str::to_owned).collect();

and formatting turns it into

```
let names = String::from_utf8(names)
    ?
    .split('|')
    .map(str::to_owned)
    .collect();
```

instead of

```
let names = 
    String::from_utf8(names)?.split('|').map(str::to_owned).collect();
```

which is how it gets formatted if I omit the "?" operator. And I have checked: increasing max_width in rustfmt.toml has no effect.

**Comment by topecongiro** [comment]
Using rustfmt 0.8.1, the chain without '?'
```rust
let names = String::from_utf8(names).split('|').map(str::to_owned).collect();
```
formats to
```rust
    let names = String::from_utf8(names)
        .split('|')
        .map(str::to_owned)
        .collect();
```
so I assume that the problem is '?' occupying the whole line.

Changing [this line](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/chains.rs#L220)
```rust
 } else if let ast::ExprKind::Try(_) = subexpr_list[0].node {
```
to
```rust
} else if rewrites[0] == "?" {
```
solves the problem, though they theoretically ought to mean same thing...

Also the relavant paramter is `chain_one_line_max` which is set to 60 by default.
