### ISSUE TITLE
Format removes empty tuples from Impl but not from enum

### ISSUE THREAD

**Issue by gabisurita** [rust-lang-nursery/rustfmt#1408]
I had something like

```rust
use std::convert::Into;

/// Known paths
pub enum Paths<'a> {
    Batch(),
    Buckets(),
    Bucket(&'a str)
}

impl<'a> Into<String> for Paths<'a> {
    fn into(self) -> String {
        match self {
            Paths::Batch() => format!("/batch"),
            Paths::Buckets() => format!("/buckets"),
            Paths::Bucket(id) => format!("/buckets/{id}", id = id),
        }
    }
}
```

After running format, it removed the empty tuples from the implementation match but not from the the enum definition. Leading to some errors. You can see the format result and the compiler output. 

```rust
use std::convert::Into;

/// Known paths
pub enum Paths<'a> {
    Batch(),
    Buckets(),
    Bucket(&'a str)
}

impl<'a> Into<String> for Paths<'a> {
    fn into(self) -> String {
        match self {
            Paths::Batch => format!("/batch"),
            Paths::Buckets => format!("/buckets"),
            Paths::Bucket(id) => format!("/buckets/{id}", id = id),
        }
    }
}
```
```
gsurita-30820:kinto-http.rs gsurita$ RUST_TEST_THREADS=1 RUST_BACKTRACE=1 cargo test 
   Compiling kinto_http v0.1.0 (file:///Users/gsurita/kinto-http.rs)
error[E0532]: expected unit struct/variant or constant, found tuple variant `Paths::Batch`
  --> src/paths.rs:21:13
   |
21 |             Paths::Batch => format!("/batch"),
   |             ^^^^^^^^^^^^ not a unit struct/variant or constant

error[E0532]: expected unit struct/variant or constant, found tuple variant `Paths::Buckets`
  --> src/paths.rs:22:13
   |
22 |             Paths::Buckets => format!("/buckets"),
   |             ^^^^^^^^^^^^^^ not a unit struct/variant or constant
```

**Comment by alobb** [comment]
I have a fix that also removes the parens from the enum declaration, which means that `Batch` and `Bucket` would be unit variants instead of empty tuples, and the given code will compile after being run through rustfmt. @nrc , would it be preferable to instead fix it the other way (i.e., change rustfmt so that the match arm stays as an empty tuple, rather than becoming a unit variant)?  I'm not sure if this transformation could unintentionally modify the meaning of the code.

Additionally, with my fix, several tests fail (output attached), which seems to indicate that either (1) this wasn't considered before or (2) we don't want rustfmt to convert empty tuple to unit variant.

[testOutput.txt](https://github.com/rust-lang-nursery/rustfmt/files/869770/testOutput.txt)

**Comment by nrc** [comment]
> would it be preferable to instead fix it the other way

Yeah, definitely. The two are technially different and Rustfmt should strive to never change the semantics of programs.
