### ISSUE TITLE
v8.1 is mistagged

### ISSUE THREAD

**Issue by mkantor** [rust-lang-nursery/rustfmt#1475]
Not sure if you want to do anything about this, but I noticed that there's tag in the repo named `v8.1` that should probably be `v0.8.1`. This points to commit 7377dfc38c932949f26e99016f491ae3a81db6b2 which also mistakenly mentions `v8.1` in its commit message.

Tangentially, is there any semantic difference between the `v*` tags and the unprefixed version tags? There are some of each here.

**Comment by mkantor** [comment]
I notice there's also a `v0.8.1` tag that refers to the same commit.

**Comment by nrc** [comment]
Yeah, I kind of screwed this up (also sometimes using a `v` and sometimes not is a screw-up too). However, I think any fix is worse than leaving this unfixed, so I'll just jump from v7 to v9 or something.

**Comment by rpsrosario** [comment]
I know this is and old issue, but the presence of the `v8.1` tag leads to the breakage of scripts that try to identify the latest semantic version of the repository.

Take for example something along the lines of:
```sh
tag=$(git ls-remote --refs --sort=-v:refname https://github.com/rust-lang/rustfmt.git 'refs/tags/v*' | head -n 1 | sed 's:.*refs/tags/v::')
git clone https://github.com/rust-lang/rustfmt.git --branch v$tag --depth 1
```

This would wrongly clone the `0.8.1` version since the `v8.1` tag would be identified as the latest semantic version.

@nrc would it be possible to actually remove this tag?

**Comment by calebcartwright** [comment]
The v8.1 tag has been removed
