### ISSUE TITLE
Configuration option to specify required version

### ISSUE THREAD

**Issue by leoschwarz** [rust-lang-nursery/rustfmt#1505]
One thing that has just happened to me and might very well have occured to others already too, is that with a global installation of rustfmt it's easy to lose track of the version numbers and due to changes between the versions the same changes will be done and undone every time you switch the version accidentally.

Maybe by specification of a required version number in the `rustfmt.toml` file this could be resolved. If a number is specified and the user has the wrong one rustfmt could just refuse to do anything and report an error. A user can then either change the config file or update to the required version.

**Comment by gnzlbg** [comment]
I also have this problem, and its an issue when multiple collaborators are working on a single project, and each of them is using a different rustfmt version... 

Ideally this would be tightly coupled with cargo, so that it can automatically install the appropriate rustfmt version for each project.

**Comment by japaric** [comment]
This is an interesting issue.

The rustup solution seems hard to maintain: today, rustfmt is coupled to libsyntax which means that
it will only work with the toolchain it was built with (due to unstable ABI / metadata format). This
also means that to implement this the rust-lang/rust build system would have to produce *N* versions
of rustfmt for *each* toolchain every day. Today we have more than 20 toolchains for all sort of
platforms (Linux, macOS, \*BSD, Windows, Android, etc.) this means 20\*N rustfmt daily artifacts.
How big will N be? 5? 10? 20? N will only grow as time goes by.

Now, IIRC, to improve nightly releases these toolchain artifacts are actually not built daily but
for *every* tested / merged PR. I expect that we'll do the same for the rustfmt artifacts. This
means adding *N* rustfmt build times to each CI builder that builds a toolchain; depending on the
size of N this could reduce the number of PRs we can merge in a day.

However, in theory, none of this will be a problem once rustfmt reaches 1.0.0 because everyone will
be using that version. And I expect that using release 1.x.y won't be much different if you are
using the stock configuration. The question is if, and how, we should address the version problem
until 1.0.0 is released (which probably is still months away). IMO, the version requirement in
rustfmt.toml sounds like an OK solution for a temporary problem.

(I'm wondering if the rustfmt distribution issue can be made more tractable if we *statically* link
rustfmt to libsyntax et al.; that should decouple rustfmt from the toolchain letting us have rustfmt
releases independent of toolchain releases so no need to re-release rustfmt on a nightly basis.)

**Comment by gnzlbg** [comment]
> However, in theory, none of this will be a problem once rustfmt reaches 1.0.0 because everyone will be using that version.  And I expect that using release 1.x.y won't be much different if you are
using the stock configuration. 

Every bugfix to rustfmt can potentially change the formatting. If you want to use it in any sort of integrated CI, this is a problem, because e.g. your CI might be using a version that is slightly different than yours :)

**Comment by japaric** [comment]
> Every bugfix to rustfmt can potentially change the formatting.

> your CI might be using a version that is slightly different than yours

That sounds like either you or the CI is using a buggy version. The way I see it is: post 1.0, if you change the rustfmt version *while keeping your formatting options the same* and get a different formatted output then that's a bug.

IMO, we should encourage people to *not* use buggy versions (e.g. by yanking them), instead of giving them a way to manage multiple installs of *buggy* versions using rustup.

I do hope that a requirement for the 1.0 release is that the stock configuration is relatively bug free (i.e. that we are happy with how it formats code in most scenarios).

**Comment by gnzlbg** [comment]
This means that if rustfmt 1.0 formats some weird corner case improperly,
then that corner case cannot be fixed afterwards as a bug.

FWIW clang format is 5 years old, bugs that alter the formatting in weird
corner cases are still fixed weekly.

**Comment by boozook** [comment]
[There](https://github.com/rust-lang/rustfmt/blob/041f11315923b0e4b0328b3bb6366de9148c7b6b/src/config/mod.rs#L217) should be semver match instead of just `eq`, I suppose.
