### ISSUE TITLE
Any way to match `=`s?

### ISSUE THREAD

**Issue by legolord208** [rust-lang-nursery/rustfmt#1566]
I would find it really cool to have a switch that takes

```Rust
let hi = "Hi";
let world = "World";
```

into

```Rust
let hi    = "Hi";
let world = "World";
```

Cheers!

**Comment by nrc** [comment]
Alignment of this kind has been mentioned before, usually in the context of `=>` in `match` or similar. This is harder than that because the `=` are in two separate statements and Rustfmt works one AST node at a time. The general problem is tricky for non-technical reasons - how do you know when to align things? Do whitespace or comments stop aligning? How hard should we try to keep alignment vs keep the code on one line? Etc. Given the hard non-technical questions and the difficulty of implementation in general, I don't think this will ever get done, not because I object on principle, but because there are so many other things to get done first.
