### ISSUE TITLE
rustfmt is not tested to be idempotent

### ISSUE THREAD

**Issue by behnam** [rust-lang-nursery/rustfmt#1675]
If I understand correctly, `rustfmt` is expected to be idempotent, meaning that it should not change the content after one run. (Please let me know if that's not the case.) But looks like it's not tested to maintain this property.

And, besides maintaining idempotency, such tests can also surface bugs like this during dev/ci: https://github.com/rust-lang-nursery/rustfmt/issues/1674

**Comment by nrc** [comment]
We do test for idempotency by running the 'target' of every test through rustfmt as a 'source'. Obviously, this only catches bugs if there is a relevant test. We also test rustfmt on its own source code, so this should also catch any non-idempotency bugs as a side-effect. I'll close this issue for now because I don't know of any way to improve this testing, but if you think of something I can re-open.
