### ISSUE TITLE
Prefer keeping `unsafe {` on its own line

### ISSUE THREAD

**Issue by pornel** [rust-lang-nursery/rustfmt#1685]
I write:

```rust
unsafe {
    dangerous_operation()
};
```

to make `unsafe` more visible on its own line, and the unsafe expression to be visually separate from the safe code surrounding it.

rustfmt is eager to remove whitespace around `unsafe {}`, and even fold it into surrounding safe code:

```
do_something(unsafe { dangerous_operation() });
```

I'd prefer if line break after `unsafe {` was preserved. 

I don't always insist on putting unsafe code on separate line, e.g. for C FFI calls that I think are safe enough. But IMHO trasmutes and pointer casts deserve to be made clearly stand out by putting them on their own line.

**Comment by nrc** [comment]
The rule here (and it is the same for some other kind of blocks) are that we put it on one line if there is a single expression, no statements, and no comments. So `unsafe { dangerous_operation(); }` would be split across multiple lines. This is obviously a compromise between visibility when you want it and conciseness when you don't. This was discussed here: https://github.com/rust-lang-nursery/fmt-rfcs/issues/21 (though I think some of the pertinent discussion was in a meeting rather than inline).
