### ISSUE TITLE
Function calls should sometimes try putting arguments on each line rather than multi-lining individual args

### ISSUE THREAD

**Issue by BusyJay** [rust-lang-nursery/rustfmt#1697]
for example:

```
fn main() {
    Test.func_a(A_VERY_LONG_CONST_VARIABLE_NAME, move |arg1, arg2, arg3, arg4| arg1 + arg2 + arg3 + arg4)
}
```

Should it be formatted as

```
fn main() {
    Test.func_a(A_VERY_LONG_CONST_VARIABLE_NAME, move |arg1,
          arg2,
          arg3,
          arg4| {
        arg1 + arg2 + arg3 + arg4
    })
}
```

or

```
fn main() {
    Test.func_a(
        A_VERY_LONG_CONST_VARIABLE_NAME,
        move |arg1, arg2, arg3, arg4| arg1 + arg2 + arg3 + arg4
    )
}
```
?

I personally prefer the later way, because it allows the closure be in one line when possible.

**Comment by nrc** [comment]
I also prefer the latter in this case.

I think the error here is that usually, once a function call goes multi-line, we put each argument on its own line. However, we special case the final argument and allow the args to stay on one line, if only the last arg goes multi-line. This is for cases like:

```
foo(a, b, c, || {
    // a 
    // long
    // body
});
```

Where this looks better than putting `a, b, c` each on their own line. However, in OP's case this heuristic fails because the closure body is small and the args are long and the closure formatting is thus suboptimal.

It is probably worth spreading the args to `func_a` in this case. But I'm not really sure how to do that. Formatting the closure could fail if it thinks it is looking ugly (e.g., if the arg block is longer than the body or something). Then the outer item would have to create more space. However, sometimes we can't make more space, and so we'd fail when we could have succeeded. The other option is instead of just formatting or failing to format, we could have a confidence level (so we can express 'we succeeded to format, but it looks bad. If you have to use this, do so, but if there is a better way, try that') - that is a better solution but would be a large and far-reaching refactoring.

**Comment by BusyJay** [comment]
I think the rule can be simplified as:

1. if all the remaining args fit in one line, do it;
2. from first arg to the last, if it's a closure:
  1) if all preceding args and the closure's args can't fit in one line, format all args with block style;
  2) otherwise put the closure's body into a block;
  3) go to step 1 again;
3. if no closure is found, format all args with block style.
