### ISSUE TITLE
Macro call formatting

### ISSUE THREAD

**Issue by theotherphil** [rust-lang-nursery/rustfmt#1712]
The default rustfmt settings convert this:

```
let image = gray_image!(
    00, 01, 02;
    10, 11, 12;
    20, 21, 22);
```

into this:

```
let image = 
    gray_image!(
    00, 01, 02;
    10, 11, 12;
    20, 21, 22);
```

Is this deliberate, and if so which rule is controlling this? I'm not particular fussed about the formatting either way, but I don't want to reformat all my code if this is liable to change in the near future.

According to @steveklabnik: "seems like a bug to me, but I am not sure".

**Comment by topecongiro** [comment]
rustfmt uses some heuristic when right hand side of an assignment is a macro. Unfortunately when the macro contains an invalid syntax, the heuristic forces the macro to be places on the next line. #1719 should fix this.

**Comment by theotherphil** [comment]
Could you clarify what you mean by "invalid syntax"? The code compiles fine, but presumably you mean something other than "would be rejected by the compiler".

**Comment by topecongiro** [comment]
Sorry for the confusion. By "invalid syntax" I mean that the arguments of macro does not "look like" function call.

So rustfmt needs to parse the token stream of macro arguments and reconstruct AST before reformatting.
This parsing only succeeds if the macro "looks like" function call (an exception is `vec![expr; expr]`).
For the above example, the parsing fails because it has `;` in it.

Is this clear to you?

**Comment by theotherphil** [comment]
Yes, thanks for the explanation :-)
