### ISSUE TITLE
trailing commas inconsistently added after function arguments

### ISSUE THREAD

**Issue by mulkieran** [rust-lang-nursery/rustfmt#1865]
https://travis-ci.org/stratis-storage/devicemapper-rs/jobs/261884820 has some examples. See line 1805, 1792, and others.

In most function calls, a comma is added after the last argument, as well as after the preceding arguments. But in some cases this does not happen, for reasons perhaps related to the syntactic structure of the argument.

**Comment by nrc** [comment]
All the examples I could find (including 1805 and 1792) were macros. We don't add or remove trailing commas in macros because they can change the semantics of the macro (macros don't actually ever take a list of expressions as args, they get the tokens themselves). So I think we are consistent for function arguments and consistent (but differently) for macros.

**Comment by mulkieran** [comment]
Ok. I'm ignoring everything inside a macro, at any depth. That only leaves line 903, which pushes a tuple, but puts no comma after the tuple, as:

```
 ⏎

-                targets.push((Sectors(targ.sector_start),⏎

-                              Sectors(targ.length),⏎

-                              target_type,⏎

-                              params));⏎

+                targets.push((⏎

+                    Sectors(targ.sector_start),⏎

+                    Sectors(targ.length),⏎

+                    target_type,⏎

+                    params,⏎

+                ));⏎

 ⏎
```

**Comment by nrc** [comment]
Yep, that is deliberate too :-) There's newline after the `)` so we don't put a comma there (put another way, the call to `push` only has a single argument with no line breaks (the line breaks are internal to the argument)).
