### ISSUE TITLE
enhancement request - derive sorting

### ISSUE THREAD

**Issue by sagiegurari** [rust-lang-nursery/rustfmt#1867]
maybe like you are sorting the 'use' lines and values, you could also sort the derive values, for example

````rust
#[derive(Serialize, Deserialize, Debug, Clone)]
````

can be sorted by abc order and keep the code consistent all over.

**Comment by nrc** [comment]
We can't do this because the order of derives can be semantically important (a derive only sees following derives, so in your example, `Debug` only sees `Clone`) and re-ordering could thus break some custom derives.

**Comment by sagiegurari** [comment]
Ok didnt know

_Sent from my Lge LG-H815 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by upsuper** [comment]
Although order of derives can be semantically important, I believe majority of custom derives don't care about other derives, and it could almost certainly be surprising if a custom derive is sensitive to the order.

So I think it is probably a good idea for rustfmt to support sorting derives (maybe as an opt-in for now), and discourage custom derive to rely on its position in derive list.

There are projects, e.g. Stylo, try to sort the derives. An example can be seen [here](https://searchfox.org/mozilla-central/rev/f8b11433159cbc9cc80500b3e579d767473fa539/servo/components/style/values/generics/color.rs#87-103). Without rustfmt's help, it needs to be maintained manually, which is error-prone.

**Comment by scampi** [comment]
I didn't know before now the order is important. If a derive is sensitive to order, then I imagine the confusion from the user in case of an error.
Even if the option is an opt-in, a user may enable it knowingly but forget about it later, and would be caught by it...

**Comment by upsuper** [comment]
>  Even if the option is an opt-in, a user may enable it knowingly but forget about it later, and would be caught by it...

As I mentioned, I think it should generally be considered a bad practice to have derive order sensitive.

Doing so would surprise users anyway, given how few people are aware of it, regardless of whether rustfmt would sort it.

**Comment by thomaseizinger** [comment]
Even if there is a derive that is dependent on the order, it would be good practice by the maintainer to chose the name in a way so that the order is enforced by rustfmt :)

**Comment by marcospb19** [comment]
This would be a great option, but by default it should be turned off.

For my personal taste of the rustfmt configurations, I would turn this on, and merge_derives off, if I need a derive that is order sensitive, then I leave it on top of the other.

#[derive(SensetiveOne)]
#[derive(others... ordered!)]

**Comment by kangalioo** [comment]
This issue should be reopened. Many options could already theoretically break custom proc macros (e.g. all options that modify AST: [1](https://rust-lang.github.io/rustfmt/?search=&version=v1.5.1#force_explicit_abi), [2](https://rust-lang.github.io/rustfmt/?search=&version=v1.5.1#force_multiline_blocks), [3](https://rust-lang.github.io/rustfmt/?search=&version=v1.5.1#format_code_in_doc_comments), [4](https://rust-lang.github.io/rustfmt/?search=&version=v1.5.1#match_arm_blocks), [5](https://rust-lang.github.io/rustfmt/?search=&version=v1.5.1#match_arm_leading_pipes), [6](https://rust-lang.github.io/rustfmt/?search=&version=v1.5.1#match_block_trailing_comma), [7](https://rust-lang.github.io/rustfmt/?search=&version=v1.5.1#merge_derives)...). That is fine because proc macros shouldn't depend on such details and deserve to break if they do. Same applies here.

Plus, this option would be opt-in anyways, so users would know what they're getting into when enabling this option.

It would be nice to have this option [for serenity](https://github.com/serenity-rs/serenity/pull/2167#discussion_r978261183)

**Comment by joao-conde** [comment]
Any updates on this? Think this is really nice to bring consistency to codebases (less cognitive load when reading code too).

**Comment by epilys** [comment]
@joao-conde https://github.com/dcchut/cargo-derivefmt

**Comment by joao-conde** [comment]
> @joao-conde https://github.com/dcchut/cargo-derivefmt

Seems to be a simple sorting tool only, which doens't address the problem of  some derives that depend on others, where order matters, right?
