### ISSUE TITLE
Check for license

### ISSUE THREAD

**Issue by marcusklaas** [rust-lang-nursery/rustfmt#209]
License should probably be a configuration option.

cc https://github.com/nrc/rustfmt/issues/20

**Comment by scyptnex** [comment]
Working on this.

In my current implementation, the user specifies if they want the license to be from a file (license_policy="FileLicense") or a string (license_policy="TextLicense"), Since rustfmt's top-of-src license directs you to the 'file at the top level of this distribution', it would be a TextLicense.

There are some implications concerning the default configuration for this code, specifically, what is a reasonable *default behaviour* for the license?

Also there are legal implications, This code could be used to keep the licenses for an entire codebase up to date, but the result is that it overwrites some license that is at the top of a file.  A naive user could accidentally overwrite someone else's license with their own

**Comment by marcusklaas** [comment]
My initial idea was that we would simply warn on a missing (or inconsistent) license. Keeping licenses up to date by hand shouldn't be too much work and your last point certainly is significant as well.

**Comment by kamalmarhubi** [comment]
This sounds fiddly. Copyright dates in license headers will differ across a codebase for example. Could you define more clearly how you're thinking this would work? I can imagine:
- heuristically track license headers and warn if they're inconsistent (user friendly, but probably a messy implementation to not be noisy)
- some kind of optional template for a comment that must appear at the top of source files

**Comment by nrc** [comment]
The latter - user supplies a license template, we check for it on every file, warn if one is missing. Added extra - default template values and insert a license where it is missing.

**Comment by opilar** [comment]
Hi! Seems no progress. I would like to take it.
Can someone to help me with the implementation?
I don't know how to add this rule. 
How user should supply a license template?

**Comment by nrc** [comment]
Implementation steps (kinda guesswork, feel free to change as needed)

* add a `license_template` config option which specifies a path to a license template file
* add code to the driver (lib.rs) which if that option is set, and the path can be read, adds the template to the context before we start formatting.
* add code to the driver such that when we start formatting a new file, we call a new function `check_license` on that file
* `check_license` should return early if there is no template
* to start with, just check that the file starts with the license template
* then add templating features - for a first PR, I would allow `{}` in the template and interpret this to mean any text. This should be easy to implement using a regex and replacing `{}` with `.*`. The tricky thing is escaping the license text (which is why I don't propose using a regex for the template).

@opilar let me know if you have any questions and thanks for jumping on this!

**Comment by dlukes** [comment]
I hope you don't mind, but since there hasn't been any activity on this since September, I took a stab at this :) Trying to learn to find my way around other people's Rust code. I hit some snags though and I can't seem to come up with a satisfactory solution, please see #2456!

**Comment by dlukes** [comment]
I think this can be closed now in light of #2456? :)
