### ISSUE TITLE
Can I disable rustfmt on chaining?

### ISSUE THREAD

**Issue by VioletRainbows** [rust-lang-nursery/rustfmt#2095]
Hello,

Is there a way to disable rustfmt for function chaining?

It really feels to me that there is no one-size-fit-all solution for chain formatting. In my experience (limited in rust), it is mostly a case by case basis.

Here is a piece of code that I do not want to be formatted as a example:

**With rustfmt**
```rust
    while {
        let count = fread.read(bytes.as_mut_slice()).unwrap();
        fwrite
            .write(
                // Convert from ISO-8859-1 (latin-1) to UTF-8
                ISO_8859_1
                    .decode(&mut bytes[0..count], DecoderTrap::Strict)
                    .unwrap()
                    .as_bytes(),
            )
            .unwrap();
        count == BUFSIZE
    }
    {}
```

**Manually**
```rust
    while {
        let count = fread.read(bytes.as_mut_slice()).unwrap();
        fwrite.write(
            // Convert from ISO-8859-1 (latin-1) to UTF-8
            ISO_8859_1
                .decode(&mut bytes[0..count], DecoderTrap::Strict)
                .unwrap()
                .as_bytes(),
        ).unwrap();
        count == BUFSIZE
    } {}
```

**Comment by nrc** [comment]
There is no way (currently) to disable rustfmt for some kinds of expression but not others. You can use a skip annotation to skip a single statement, so that might be the best thing to do in your case.

There are various difficulties with maintaining the original source: whether to and how to move the source if the surrounding statements are reformatted, affecting the idempotence of reformatting, interaction with warnings about line length, etc. So although this is a reasonable request I don't think we can easily (or should) implement it, sorry.
