### ISSUE TITLE
Use a command line argument parsing library

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#213]
Are there any objections to using a command line argument parsing library as opposed to doing the parsing manually? I'd recommend [getopts](http://doc.rust-lang.org/getopts/getopts/index.html), as it's flexible enough to do things like doing our own handling when an incorrect argument is encountered.

**Comment by nrc** [comment]
The slightly tricky thing here is that most command line arguments are simply passed to rustc, rather than being used by rustfmt. As long as the library can handle that, then it seems like a good idea to use one (although I had originally hoped that rustfmt would not need to take any command line args, other than the ones we passed to rustc).

**Comment by scyptnex** [comment]
Is this still a priority? (or were you going to close it?)

**Comment by crumblingstatue** [comment]
I don't think this is a priority, but it could be implemented in the future, so I'm going to keep it open.
