### ISSUE TITLE
Error loading shared libraries.

### ISSUE THREAD

**Issue by bltnkl** [rust-lang-nursery/rustfmt#2322]
I have nightly installed and set to default. I also have rustfmt-nightly installed.

`export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH` is the last line in `.profile`(bash) .
However, when I run `rustfmt -V` I get error about loading libsyntax_some_alphanumeric_sequence_.so
It worked after I `uninstall`ed/`install`ed rustfmt-nightly.

Seems that rustfmt-nightly breaks after nigthly update, because name of libsyntax(that is part of compiler) changes, and rustfmt-nightly can no longer find libsyntax searching by old(libsyntax of previous nightly build) name.

Is it expected behaviour? Necessity to rebuild is annoying, even more, it seems that it requires rebuild of another libraries rustfmt-nightly is dependent on.

**Comment by topecongiro** [comment]
Unfortunately this is expected behavior.

If you are using rustup 1.8.0 or later, you could add rustfmt by `rustup component add rustfmt-preview`. With rustup you need not rebuild rustfmt every nighlty update. However, whenever there is a breaking change in libsyntax library (a parsing library in rustc which rustfmt depends on), rustfmt will be unavailable for several days until rustfmt gets updated. During that time you need to reinstall rustfmt via cargo. The whole mess should be fixed once rustfmt reaches 1.0. For now, please bare with the inconvenience.
