### ISSUE TITLE
Add a support for immovable generators

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#2397]
For example, when I try to format the following code,

```rust
#![feature(generators)]

unsafe fn foo() {
    let mut g = static || {
        yield 3;
    };
}
```

rustfmt 0.3.6-nightly emits the following error:
```
error: expected expression, found keyword `static`
 --> test.rs:4:17
  |
4 |     let mut g = static || {
  |                 ^^^^^^

```

The procedure to fix this would be something like this:
1. add tests to make sure that rustfmt handles immovable generators
2. update `rustc-ap-syntax` and `rustc-ap-rustc_errors` to the latest version
3. update expr.rs and closures.rs to support immovable generators

cc https://github.com/rust-lang/rust/pull/45337

**Comment by topecongiro** [comment]
BTW it feels great that rustfmt was not affected by the breaking change in libsyntax 🙌

**Comment by csmoe** [comment]
I wanna take this, but is it suitable for me with basic Rust learned from *The Rust Programming Language(2nd)* and *Rust By Example* ?

**Comment by nrc** [comment]
@csmoe probably! Have a pole around the code base, and see if the steps in the OP make sense, the first two are testing, and Cargo only. The third requires writing some code. Let us know how you get on - if it feels too overwhelming, have a play with the code in general - try refactoring some small things to get an idea how the code works and if this bug is fixed, ping us and we'll find you another!

**Comment by csmoe** [comment]
@nrc thank you,I’ll try my best on this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by csmoe** [comment]
I have updated `rustc-ap-syntax` and `rustc-ap-rustc_errors` to the latest version.
But the latest `rustc-ap-syntax = "26.0.0"` introduced a new struct inside `ast.rs`:
```
pub struct Label {
    pub ident: Ident,
    pub span: Span,
}
```
to replace the function provided by `syntax::codemap::Spanned` in `rustc-ap-syntax = "12.0.0"`.
So it broke some piece of code: 
```
error[E0609]: no field `node` on type `syntax::ast::Label`
   --> src/expr.rs:140:53
    |
140 |                 Some(ident) => format!(" {}", ident.node),
    |                                                     ^^^^ unknown field
    |
    = note: available fields are: `ident`, `span`

error[E0609]: no field `node` on type `syntax::ast::Label`
   --> src/expr.rs:147:53
    |
147 |                 Some(ident) => format!(" {}", ident.node),
    |                                                     ^^^^ unknown field
    |
    = note: available fields are: `ident`, `span`

error[E0277]: the trait bound `str: std::marker::Sized` is not satisfied
   --> src/expr.rs:297:20
    |
297 |         .and_then(|expr_str| {
    |                    ^^^^^^^^ `str` does not have a constant size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `str`
    = note: all local variables must have a statically known size

error[E0308]: mismatched types
   --> src/expr.rs:755:57
    |
755 |             Some(ControlFlow::new_for(pat, cond, block, label, expr.span))
    |                                                         ^^^^^ expected struct `syntax::codemap::Spanned`, found struct `syntax::ast::Label`
    |
    = note: expected type `std::option::Option<syntax::codemap::Spanned<syntax::ast::Ident>>`
               found type `std::option::Option<syntax::ast::Label>`
```
It can be fixed with some modifications, is it ok to enclose these modifications into commits for this issue(I'm uncertain because this bug is introduced by `rust-ap-syntax` but unrelated to `immovable_generator`)?

**Comment by topecongiro** [comment]
@csmoe It is perfectly ok to do so. If you have any trouble, please feel free to use [this branch](https://github.com/topecongiro/rustfmt/tree/update-rustc-ap).
