### ISSUE TITLE
Struct instantiation always multiline

### ISSUE THREAD

**Issue by Keats** [rust-lang-nursery/rustfmt#2425]
I have lots of these changes in my tests:

```diff
-    let start_ws = WS { left: true, right: true };
-    let end_ws = WS { left: true, right: true };
+    let start_ws = WS {
+        left: true,
+        right: true,
+    };
+    let end_ws = WS {
+        left: true,
+        right: true,
+    };
```

The struct literals clearly fit in a line (only 4 spaces before the `let`), which should be ok according to https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/expressions.md#struct-literals

Happens in patterns as well:

```diff
-            Node::If(If {conditions, otherwise}, end_ws) => {
+            Node::If(
+                If {
+                    conditions,
+                    otherwise,
+                },
+                end_ws,
+            ) => {
```

**Comment by nrc** [comment]
This is expected - we have a heuristic cut-off for when to put structs on a single line (which is what the spec means by *small*), so `let end_ws = WS { x: 0, y: 0 }` would end up on one line, but your examples are too wide. We will probably in the future make the *small* heuristic smarter in order to deal with small (but not very small) struct lits where the fields are very simple.
