### ISSUE TITLE
Are you aware of rust-style?

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/rustfmt#249]
https://github.com/sp0/rust-style

Maybe there are things to be learned from it.

**Comment by nrc** [comment]
Yes, it is based on the approach of using a token stream rather than using the AST. They have their own pseudo parser. Because of the different approaches, I don't think there is much we can share. The exception might be macros - I wonder if their approach to macros could be used without taking the rest whole-sale? It might also be worth sharing some test cases between the two projects.
