### ISSUE TITLE
Preserve user format when formatting large expression lists

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2555]
When I write

```rust
let x = i8x16::new(
    0, 1, 2, 3, 4, 5, 6, 7,
    8, 9, 10, 11, 12, 13, 14, 15
);
``` 

it would be really really awesome if rustfmt could recognize that:

* there is a list of arguments that is large
* the user has arranged in a particular way: nxm matrix with n = 2 and m = 8.
* (maybe that the arguments all have the same type?)

and then preserve this particular arrangement while formatting the code. In particular when not doing so would make the number of lines of the item being formatted explode:

```rust
let x = i8x16::new(
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
    );
```

This heuristic could be opt-in. Otherwise code that uses lots of arrays or similar things like SIMD vectors becomes full of `#[cfg_attr(rustfmt, skip)]` annotations. This is basically the only remaining major issue I have with `rustfmt`.

**Comment by topecongiro** [comment]
cc #2196, #2418.

**Comment by gnzlbg** [comment]
I found https://github.com/rust-lang-nursery/rustfmt/issues/2196 before filling this one, but this doest not propose to use an heuristic to format these, but rather to preserve the previous formatting. An heuristic to identify these is still required.

**Comment by topecongiro** [comment]
Yes, I am aware of the differences, I just mentioned them so that we need not duplicate discussion :)

In general, rustfmt tries to avoid relying on user's input because it violates consistent formatting. AFAIK currently we only rely on comments or strings. However, I think this heuristic is fine to have by default as long as we only apply this to very large arguments.

I have implemented a draft version in [this branch](https://github.com/topecongiro/rustfmt/tree/aligned-items). Would you mind trying this, please?

**Comment by nrc** [comment]
> In general, rustfmt tries to avoid relying on user's input because it violates consistent formatting

I just want to really stress this invariant in rustfmt's design - it's really important because without it, it is difficult (not impossible, but in practice, very difficult) to guarantee that Rustfmt is idempotent. That means churn in code for users and makes rustfmt impossible to use to 'check' formatting in CIs.

It's also important since we sometimes use rustfmt to format totally unformatted code (such as when generating code for refactoring, etc.) in which case we might have what looks like a really long expression and we really don't want to preserve the formatting.

**Comment by gnzlbg** [comment]
Makes sense. I hope that it also makes sense that annotating math-like code every couple of lines with a extremely verbose annotation like  `#[cfg_attr(rustfmt, skip)]` is painful.
