### ISSUE TITLE
rustfmt breaks short lines when max_width is less than 100

### ISSUE THREAD

**Issue by tspiteri** [rust-lang-nursery/rustfmt#2644]
When max_width is set to 80, lines that are shorter than 80 characters and would not be broken up with the default settings are broken up. For example with the default 100 characters I get
```rust
fn foo(e: Enum) {
    match e {
        Enum::Var { element1, element2 } => {
            return;
        }
    }
}
```
But with max_width set to 80, I get
```rust
fn foo(e: Enum) {
    match e {
        Enum::Var {
            element1,
            element2,
        } => {
            return;
        }
    }
}
```
I think the reasoning behind that is that if users want narrower lines, give them narrower blocks too. But I really don't think that is good reasoning. If I use a max width of 80, it's not because I want to have more lines, but because I want my lines to fit in 80 characters. I still want my lines to be as close to 80 characters as possible without hurting readability, and in this example, the first case reads better than the second.

Are there any users who actually expect blocks to be narrower as well when using an 80 maximum? If anything, I would expect 80 characters to be more old-terminal-friendly, where you would actually like less lines, not more lines, as long as the lines fit within the limit.

**Comment by nrc** [comment]
This is due to our 'small' heuristic being specified as a percentage of the max width. Note that the change in formatting is only whether we use the more compact form or not.

This was changed in https://github.com/rust-lang-nursery/rustfmt/pull/2428, there wasn't much discussion of whether this was a good idea or not. I can see arguments in both directions. 

@topecongiro what's your opinion on this?

**Comment by cmbrandenburg** [comment]
I too ran in to this problem. Sounds to me like there are two distinct uses cases at work here, and `rustfmt` is doing a poor job of covering both cases because it's overloading one option to denote two different things.

1. A hard limit on line length, e.g., an 80-column length limit.
2. A “heuristic width” option as a general hint to `rustfmt` for the width of _all_ lines.

A big part of use case 1 is for people with small monitors. Overloading `max_width` for use case 2 needlessly wastes space by splitting lines that are already shorter than the maximum. This further exacerbates the problem of having a small monitor because it can cause fewer logical lines to fit on one screen. It's not just the columns that are precious on a small monitor; rows are precious too.

**Comment by topecongiro** [comment]
I originally proposed to use relative values in #2206. IIRC the original motivation was to provide a good width heuristic when the max width is **larger** than the original value, because otherwise the heuristics may be too strict.

From my experience, using relative values to the max width for width heuristic performs well when the max width is slightly larger than the default (e.g. 120), though it may perform poorly in some extreme cases (e.g. when the max width is set to 200, too long function calls get put in a single line). I have not used the max width smaller than the default, so have not noticed this issue.

I think that the downside of using relative width is bigger than the upside. I think we should switch back to use fixed values, or use relative values only when the max width is larger than the default.

**Comment by tspiteri** [comment]
I like the idea of using relative values only when the max width is larger than the default.
