### ISSUE TITLE
Unexpected string literal indents

### ISSUE THREAD

**Issue by kbacha** [rust-lang-nursery/rustfmt#2695]
Rust 1.26 was just released and it appears to have changed some aspect of rustfmt as well. I ran `cargo fmt` on my repo (https://github.com/kbacha/stellar-sdk) and pushed the changes. However, it failed on CI because of a format issue. We run a format check so that we don't merge poorly formatted code:
https://travis-ci.org/kbacha/stellar-sdk/builds/377478444?utm_source=github_status&utm_medium=notification

![image](https://user-images.githubusercontent.com/2043529/39896729-3647ae2c-5464-11e8-9447-68bb6f612dd5.png)

I went local again and ran cargo fmt again and got:

![image](https://user-images.githubusercontent.com/2043529/39896758-52120e18-5464-11e8-83c0-f298b3750af7.png)
 and again:
![image](https://user-images.githubusercontent.com/2043529/39896771-5b70e4ca-5464-11e8-953e-5179c7904d0f.png)

Then I moved to another repo and recreated it here:
https://github.com/kbacha/cargo-fmt-err-1-26

It appears to only matter inside a macro_rules as far as I can tell.

**Comment by topecongiro** [comment]
Thank you for filing an issue!

I think that this is already fixed via https://github.com/rust-lang-nursery/rustfmt/pull/2589, but unfortunately the latest stable version (`rustfmt 0.4.1-stable (7a80726 2018-04-20)`) does not include the change.
Would you mind trying the nightly version of rustfmt? The issue should be fixed with it. Please refer to https://github.com/rust-lang-nursery/rustfmt#quick-start for how to install and use it.

**Comment by kbacha** [comment]
Yep, it does appear that it isn't broken in the nightly version. When do you think the next version will release?

**Comment by topecongiro** [comment]
AFAICT stable rustfmt shipped by rustup is infrequently update, only when the new rustc version is released. So I think that we have to wait for the next rustc's 1.27 release to see stable rustfmt gets updated.
Ping @nrc for more information, do you have a clear view on how rustup chooses the rustfmt version?

**Comment by nrc** [comment]
The version rustup chooses is the submodule on the branch in the Rust repo. We can't change that in stable/beta without doing a point release of Rust itself, which I don't think we can get away with for this.

Going to close this issue since it is fixed on master. As a work around I would recommend using beta or nightly, just for rustfmt'ing
