### ISSUE TITLE
newline_style = "Native" + wrap_comments = true introduces extra characters into comment

### ISSUE THREAD

**Issue by iliekturtles** [rust-lang-nursery/rustfmt#2728]
The following issue seems to be limited to Windows. I'm unable to reproduce on Linux. Both `newline_style` and `wrap_comments` need to be set to cause the problem.

Starting with the following `rustfmt.toml`
```toml
newline_style = "Native"
wrap_comments = true
```

and the following `src/main.rs`
```rust
//! ```rust
//! extern crate uom;
//! ```

fn main() { }
```

running the following command
```sh
$ cargo +nightly fmt --version && cargo +nightly fmt
rustfmt 0.7.0-nightly (bf2581bf 2018-05-17)
```

adds an extra line into `src/main.rs` (note the trailing space on the new line)
```diff
diff --git a/src/main.rs b/src/main.rs
index 8bc09f5..d137f1a 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,4 +1,5 @@
 //! ```rust
+//! 
 //! extern crate uom;
 //! ```
```

The issue was original detected in a branch of [`uom`](https://github.com/iliekturtles/uom) working on `rustfmt` setup where both a new line and a `}` are inserted. I was unable to reduce this exact behavior into a minimal example, but am including the diff below for reference.

```diff
diff --git a/src/lib.rs b/src/lib.rs
index f1c54a5..f8d00b1 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -24,7 +24,9 @@
 //! and this to your crate root:
 //!
 //! ```rust
+//!
 //! extern crate uom;
+//! }
 //! ```
```

**Comment by wada314** [comment]
I tried to take a look at it and found this is something kinda weird bug. This bug only happens if the `newline_style` is `Windows` (or `Native` in Windows environment). The only place I can find that `newline_style` is used is `replace_with_system_newlines()` function in src/lib.rs. But when I did println-debug at the beginning of that function, the text is already broken.

Is there any other place actually referring to the `newline_style` value?

Testcase:
https://github.com/wada314/rustfmt/commit/d329ffe9431861c80579544e20efb575be3ade09

**Comment by topecongiro** [comment]
The problem seems to be inside `format_code_block`:

https://github.com/rust-lang-nursery/rustfmt/blob/0ec1533054102e22a3318d08d6d42b3f2d583cea/src/lib.rs#L715-L727

Say the `newline_style` is set to `Windows`. Since `formatted` is the returned value from `format_snippet` which calls `format_input` internally, it contains `\r\n`. However `formatted[FN_MAIN_PREFIX.len()..block_len]` does not take this into account.

**Comment by wada314** [comment]
Thank you! I understood.
