### ISSUE TITLE
Poor formatting of impl header with long type and where bound

### ISSUE THREAD

**Issue by jturner314** [rust-lang-nursery/rustfmt#2746]
`rustfmt` (testing with the [playground](https://play.rust-lang.org/?gist=47d0a77f130a719dbc440a41285a4682&version=stable&mode=debug)) turns this:

```rust
impl<'seq1, 'seq2, 'body, 'scope, Channel>
    Adc12<
        Dual,
        MasterRunningDma<'seq1, 'body, 'scope, Channel>,
        SlaveRunningDma<'seq2, 'body, 'scope>,
    >
where
    Channel: DmaChannel,
{
}
```

into this:

```rust
impl<'seq1, 'seq2, 'body, 'scope, Channel>
    Adc12<
        Dual,
        MasterRunningDma<'seq1, 'body, 'scope, Channel>,
        SlaveRunningDma<'seq2, 'body, 'scope>,
    > where
    Channel: DmaChannel,
{
}
```

(Note the position of the `where` keyword.) The original is clearer and more consistent with the standard style.

**Comment by nrc** [comment]
Hmm, I think this is intentional (we generally will put 'openers' like `where` on the same line as a closing bracket. However, I agree this doesn't look so great because a margin-aligned `where` separates the where clause from the rest of the declaration.

Anyway, I think we should fix this and probably need to update the style guide too.
