### ISSUE TITLE
Document write-mode options

### ISSUE THREAD

**Issue by theduke** [rust-lang-nursery/rustfmt#2762]
It would be nice to have a table explaining the different write-modes in the README (and also in the --help output).

I'd do a PR but I need some help: what are the plain and coverage modes doing exactly?

| write-mode | description   |
| :-------------: | ---------------- |
| replace       | replaces formatted files, creating backup `filename.rs.bk` files with the original content |
|overwrite     | overwrites files without creating a backup |
|display         | print full formatted content of each file |
|plain            | ???  |
|diff| show diff of formatting changes  |
|coverage| ??? |
|checkstyle| print information in checkstyle XML format |

**Comment by csmoe** [comment]
rustfmt has move from `write_mode` to `emit_mode` since [commit](https://github.com/rust-lang-nursery/rustfmt/commit/95d6b648293b417309d0857b2a93c0cace70c53d)

checkout `emit_mode`:
 https://github.com/rust-lang-nursery/rustfmt/blob/f390626778c1bbb13911556d585850eb2fa67923/src/config/options.rs#L172-L187
`

**Comment by bradjc** [comment]
For anyone finding this issue (like me) note that:

- `--write-mode=overwrite` is the default
- `--write-mode=check` is now `--check`
- `--write-mode` is now `--emit`

**Comment by DevOrc** [comment]
I was thinking about tackling this. Should I include the info in both (readme and --help) or just under the help flag?

**Comment by bradjc** [comment]
I vote both.
