### ISSUE TITLE
Extra newline/indentation for chained methods with closure parameters

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/rustfmt#2786]
```
rustfmt 0.8.2-nightly (08da30d7 2018-06-06)
```

The call to baz seems like it should be formatted like the call to bar, but this is what rustfmt produces:

```rust
impl Thing {
    fn thing(&self) {
        foo(|a| {
            println!("a");
            println!("b");
        }).bar(|c| {
            println!("a");
            println!("b");
        })
            .baz(|c| {
                println!("a");
                println!("b");
            })
    }
}
```

**Comment by topecongiro** [comment]
cc #2773.

**Comment by nrc** [comment]
I have a fix in the works for this one

**Comment by nrc** [comment]
Ok, this is much harder than expected because I think there are competing, unsatisfiable constraints. On one hand when we have a block in the first item, we only want to indent it once:

```
foo(|| {
    sdfasdf()
})
```

And on the other, we want to indent chains:

```
foobar
    .foo
    .bar;
```

But, if there is a block in the chain, we want to indent that further:

```
foobar
    .foo
    .bar(|| {
        dsfdsfa
    });
```

But, we don't want to do that for the example above, because it makes the second and third items look different. (Also consider what happens if there is a non-block item in the chain between two block items.

I think the least worst solution is to not indent chains if the first item is a block, which, not great, but better than any alternative I've figured out.
