### ISSUE TITLE
Weird sorting order with reorder_impl_items

### ISSUE THREAD

**Issue by faern** [rust-lang-nursery/rustfmt#2792]
When having `reorder_impl_items = true` and this trait:
```rust
trait Foo {
    type Ok; 
    type Error;

    fn bar() -> Result<Self::Ok, Self::Error>;
}
```

I would expect an impl block to be reformatted into:
```rust
impl Foo for () {
    type Ok = String;
    type Error = (); 

    fn bar() -> Result<String, ()> {
        String::new()
    }   
}
```

But with rustfmt `0.8.2-nightly (08da30d 2018-06-06)` I get the following:
```rust
impl Foor for () {
    type Error = ();    // <- Not the same order as the trait declares them.
    type Ok = String;

    fn bar() -> Result<String, ()> {
        String::new()
    }   
}
```

I have not checked the code. But I suspect the associated types and constants are sorted alphabetically? For me it feels very strange to declare anything in a trait impl block differently than they are declared in the trait itself. So checking if this works as intended or is open for discussion/change.

**Comment by nrc** [comment]
This is working as intended, but I think it is unlikely that anyone wants there impl items sorted like this, so it is unlikely to ever be a default option.

**Comment by xMAC94x** [comment]
I have 2 questions regarding this:
1) It feels a bit weird that it's wanted behavior but nobody wants to use this feature because of this wanted behavior. wouldn't it be useful then to split `reorder_impl_items` into 2 options? `reorder_impl_items` that only formats the order of types, functions, macros and consts and `reorder_impl_items_tyües` that changes the format of the types alphabetically ?
2) I can't tell rustfmt to skip the reordering of a type with `#[rustfmt::skip]`
The following code does not work:
```rust
trait Foo {
    #[rustfmt::skip]
    type Ok; 
    type Error;

    fn bar() -> Result<Self::Ok, Self::Error>;
}
```
instead only this works which disables checks for the whole type:

```rust
#[rustfmt::skip]
trait Foo {
    type Ok; 
    type Error;

    fn bar() -> Result<Self::Ok, Self::Error>;
}
```
It would be useful if there is some fine granular option to skip only a certain reordering
