### ISSUE TITLE
More 'Good First Issue's?

### ISSUE THREAD

**Issue by max-sixty** [rust-lang-nursery/rustfmt#2886]
There's currently only one: https://github.com/rust-lang-nursery/rustfmt/labels/good-first-issue

I'd be up for some more rust contributions, and this seems like a reasonably well-contained project without too many complications. 

Thanks! 

(no need to leave this open once the maintainers have seen it)

**Comment by nrc** [comment]
Hey, sorry, we've been really focussed on a burn down of issues for 1.0, so there are just not very many good starter issues right now. There should be more again once we've released 1.0 and prioritised the next round of work.

If there's anything in the other issues that sounds interesting, then I can try and break it down into easier tasks. Otherwise check back (ping me!) in a month or two and I'm sure there will be things to look at.
