### ISSUE TITLE
Formatting issue with multiline strings

### ISSUE THREAD

**Issue by apiraino** [rust-lang-nursery/rustfmt#2911]
This:
```
fn main() {
    println!("
Hello, world!");
}
```

is reformatted to this:
```
fn main() {
    println!(
        "
Hello, world!"
    );
```

instead of:
```
fn main() {
    println!("Hello, world!");
}
```

tested with: 0.99.x, 0.8.1

Tried to create a `rustfmt.toml` in the project root with `format_strings = false`, nothing changed.

Not sure if related to #2876 or #564

**Comment by topecongiro** [comment]
Thanks for filing an issue. rustfmt should not do this kind of reformatting, since it changes the behavior of the original code.

**Comment by apiraino** [comment]
@topecongiro sorry, I'm confused: closing this issue means there is a workaround? Or is it solved in a newer release?

**Comment by topecongiro** [comment]
Sorry, let me elaborate. What I meant is that rustfmt is not allowed to format string literals like the above example because newlines in the string literal are significant.

If you compile & run the following snippet,

```rust
fn main() {
    println!("
Hello, world!");
}
```

it will emit:

```

Hello, world!
```

whereas if you compile & run the following snippet,

```rust
fn main() {
    println!("Hello, world!");
}
```

it will emit:

```
Hello, world!
```

Notice that the empty line is gone.

**Comment by apiraino** [comment]
oh ok, now it's clear, I was just put off by this:
```
println!(
    "    <---
```
but I guess it solves other use cases, I can live with that.

Thank you for the explaination! :+1:
