### ISSUE TITLE
In Rust 2018, `use ::foo::bar` and `use foo::bar` are distinct

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustfmt#3104]
I had a problem where rustfmt was reformatting `use ::foo::bar` to `use foo::bar` -- the problem is that, in Rust 2018, `use ::foo::bar` is sometimes needed to disambiguate:

See e.g.

```rust
mod rayon { }

use rayon::join;

fn main() {
    join(|| (), ||());
}
```

which -- in Rust 2018 -- fails with an ambiguity error ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d9e60a938bcca1136db5dac68aa99bc2)) if you have `rayon` in the prelude. Changing to `use ::rayon::join` disambiguates and is accepted ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ea4c88e314fb1435f5da6aafa21da618)).

**Comment by topecongiro** [comment]
You need to add `edition = "2018"` to rustfmt.toml. Or should rustfmt defaults to edition 2018?

**Comment by 12101111** [comment]
Why don't rustfmt read  `edition = "2018"` in `Cargo.toml`

**Comment by nrc** [comment]
OK, we need to make a decision here, I guess. I think cargo-fmt should definitely just check the Cargo.toml, and then rustfmt.toml if there is no edition specified. In principle rustfmt either as a binary or a library should be able to run independent of Cargo, so we can't rely on Cargo.toml. However, should we look for Cargo.toml if there is one? I think it is right to default to 2015, since that is what Rust does too. However, I'm not sure if that leaves us in a good place for people running rustfmt via an editor or the RLS (I think the RLS could set the edition, if it doesn't already. I assume editors can't do that?).

cc @topecongiro @scampi @YaLTeR @otavio

**Comment by otavio** [comment]
My understanding is that when Rust 2018 is released, cargo will default to it ... or am I mistaken?

If an editor would call `rustfmt` on save, it is the editor's responsibility to properly pass the `--edition` accordingly. If using `RLS` it is alleviated as the language server must be aware of the edition in use.

**Comment by otavio** [comment]
> Also: I tend to run rustfmt via the emacs integration, which may or may not be passing `--edition` etc. I think we should probably be conservative if we don't have a "positive indication" of the edition.

I do as well. I use `lsp-mode` and in this case, it relies on RLS to know about the edition in use, I assume. If the editor does it by itself, it is on its own to "discover" it and `Cargo.toml` seems to be the first logical place to look I guess.

**Comment by YaLTeR** [comment]
I agree that `rustfmt` should check `Cargo.toml` for edition (since it already checks `rustfmt.toml`, I don't see anything wrong with checking another relevant file).

As for the default behavior (no `Cargo.toml` and not specified in `rustfmt.toml`), I think defaulting to the 2015 edition is the right choice in order to stay compatible with the current default behavior. That is, if someone's currently formatting free-standing `.rs` files with default settings, they won't get sudden breakages.

I never really ran `rustfmt` from editors by itself, only through the RLS (which should be able to report the correct edition), doesn't `rustfmt` read `rustfmt.toml` when ran through editors? If not then it should probably be editors' responsibility to set the correct edition (so `rustfmt` should support a flag like that).

**Comment by topecongiro** [comment]
Todos:

- [ ] `rustfmt`: add `--edition` command line option
- [ ] `cargo-fmt`: read Cargo.toml and pass `--edition` flag to `rustfmt` if necessary

I think that when multiple editions are specified, the precedence should be
1. edition passed as command line argument
2. edition specified in Cargo.toml
3. edition specified in rustfmt.toml
4. the default edition (2015 for now)

**Comment by YaLTeR** [comment]
> 2. edition specified in Cargo.toml
> 3. edition specified in rustfmt.toml

Maybe also show a warning if it comes down to these two and they explicitly specify different editions? Like "warning: different editions specified in `Cargo.toml` and `rustfmt.toml`; using the X edition".

**Comment by nrc** [comment]
- [ ] check that there is API for passing the edition in the config and that the RLS is doing this correctly (based on Cargo.toml).

**Comment by otavio** [comment]
I'd like to inform I am looking at this issue, so there is no duplicated work.

**Comment by nrc** [comment]
- [ ] - stabilise the edition option

**Comment by otavio** [comment]
What is missing on this one?

**Comment by otavio** [comment]
I think that the API is already covered by https://github.com/rust-lang-nursery/rustfmt/commit/2eab9714e457cd5d7715a880cb4535e453e861e7. The stabilization is handled by #3134.

**Comment by nrc** [comment]
RLS part: https://github.com/rust-lang-nursery/rls/pull/1119
