### ISSUE TITLE
Sort crate:: use statements next to super:: and self::

### ISSUE THREAD

**Issue by pyfisch** [rust-lang-nursery/rustfmt#3201]
Imports from the same crate in the form `use crate::foobar` have a special prefix just like relative imports with `self` and `super`. But unlike relative imports which are moved to the start of the import list `crate` imports are sorted under c like external imports. The `crate::` imports will become a lot more common in the 2018 edition, so it would be great if the were placed at the start of the list and not among the other crates.

Found formatting:

```
use self::x;
use super::x;
use a;
use crate::x;
use z;
```

Expected formatting:

```
use self::x;
use super::x;
use crate::x;
use a;
use z;
```

As this is a formatting change it probably needs to be done before v1.0 or it can only be enabled via config.

**Comment by nrc** [comment]
Hmm, I thought we changed this already, maybe I am confused.

**Comment by pyfisch** [comment]
> This is already implemented on the master branch, but not yet available via rustup.

I guess #3130 implemented this. It was merged three weeks ago. When will it be available in nightly rust installed with rustup?

**Comment by topecongiro** [comment]
In order to make the new version of rustfmt available via rustup, we need to update the submodule in the [rust](https://github.com/rust-lang/rust) repository. The process was much easier in the past, just sending a PR that updates the submodule did work. However currently it is a bit more bothersome - AFAICT we first need to update rls (and possibly other tools that relies on `rustc-ap-*` crates), then update everything at once in a single PR. @nrc Is this correct?

**Comment by topecongiro** [comment]
There is a new check in the rustc repository that requires tools to rely on a single version of `rustc-ap-*` crates. I guess this has been introduced in order to reduce the build time. In any case, the process required to update the submodule in the rustc repository is as follows:

1. Publish a new version of rustfmt-nightly
2. Update `racer` to use the same `rustc-ap-*` crates as the new rustfmt-nightly
3. Update `rls` to use the new racer and rustfmt-nightly
4. Update the submodule in the rustc repository

**Comment by nrc** [comment]
Yep, that's correct. Its sometimes OK to update without the first few steps if it happens that we have't updated rustc-ap-syntax since the last Racer update.

I have a PR to the Rust repo almost ready, just waiting on another RLS PR to land before I submit it. Should be on nightly early next week.
