### ISSUE TITLE
match with only one non-empty arm should be `if let`

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#340]
e.g.,

```
match hint {
    Some(h) => acc.push(h),
    None => { }
}
```

to

```
if let Some(h) = hint {
    acc.push(h)
}
```

This definitely needs to be an option! And will need some funky tests, I bet there are edge cases where we can't do this.

**Comment by marcusklaas** [comment]
Would we not tread in clippy territory with such refactorings? I am not sure this should be in rustfmt's scope.

**Comment by nrc** [comment]
Clippy only points out if you should do it, rustfmt can actually make the change. Long term, I would really like for  rustfmt to do more of the stuff we rely on lints for at the moment.

**Comment by TimNN** [comment]
I've been considering implementing this and would like to share some thoughts / a potential design.

# Definitions
In the context of `match` expressions we define the following:
* An **empty arm** is an arm which is either the unit expressions `()` or an empty block `{}`.
* A **simple arm** is an arm without a predicate.
* An **empty `match`** is a `match` with only empty arms.
* A **simple `match`** is a `match` which consists of any number of empty arms and exactly one non-empty arm, which must be simple.

# Design
Optionally rewrite simple `match`es to their `if let` form. The following options are available:
```rust
enum SimpleMatchTransform {
    // Transform all simple `match`es.
    Always,
    // Transform only simple `match`es which have at most one empty arm, who's pattern must be the `_` wildcard.
    WildcardOnly,
    // Never transform simple `match`es.
    Never,
}
```

# Failures
If any of the following is present, `rustfmt` will (for now) be unable to transform a simple `match`:
* Any non-whitespace tokens between individual arms and the opening and closing braces (comments, attributes): There exists no obvious way to rewrite those.
* Any non-simple arm (that is, an arm with a predicate): While it may be good style, there is no way to know if a predicate is side-effect-free, as such there is no way to now if it can be removed without changing the behaviour of the code.

# Possible Extensions
* Rewrite empty `match`es to `let _ = $match_expr`

# Other Thoughts
* Do simple `match`es in expression position require special consideration? They would be pretty useless because they always evaluate to `()` but maybe the author planned for the match to evaluate to something else in the near future.
* I have, in the past, deliberately used `match` instead of a possible `if let` when pattern + match expressions exceeded the acceptable line length, because the syntax looks cleaner that way:
````rust
// Original
if let MaybeAnEnum::WithALongNamedVariant(and, some, parameters) = some_extremly_long_and_complicated_expression() {
}
// `if let` with line break
if let MaybeAnEnum::WithALongNamedVariant(and, some, parameters) =
    some_extremly_long_and_complicated_expression() {
}
// `match`
match some_extremly_long_and_complicated_expression() {
    MaybeAnEnum::WithALongNamedVariant(and, some, parameters) => {
    }
    _ => (),
}
```

**Comment by nrc** [comment]
@TimNN wow, that's thorough, good stuff. Comments:

> An empty arm is an arm which is either the unit expressions () or an empty block {}

You should check what happens with `()` match arms, in particular when they're used in expression position - you might need an `else` in that case or it isn't an exhaustive match. Not sure of the exact behaviour.

I would probably start without `WildcardOnly` - if someone wants it later, then add it, otherwise keep it simple.

> Rewrite empty matches to let _ = $match_expr

Why not just $match_expr; ? We could also just warn. Fine to leave this till later in any case

I hope that this can be a context-free transformation, i.e., we should not consider whether we are in expression position. If the author doesn't want the change, they can disable the option of use #[rustfmt_skip].

I think I still prefer the `if let` in the long line situation - it's still two lines shorter and the meaning is clearer. Note though that I would indent the second line of the conditional to align with the start of `Maybe...`, rather than have one tab space indent. (Not sure what rustfmt does in this case).

**Comment by nrc** [comment]
BTW, one approach to this would be to rewrite the AST then use rustfmt's existing functions on that AST - I would not do that. I would generate the code as text and hope we can get reuse by just sharing helper functions, etc.. If you go the AST route there are complications with spans, etc., and building AST is usually pretty yuck.

**Comment by TimNN** [comment]
The `WildcardOnly` option was pretty much a result from a comment I read in `clippy`, about why the simple `match` lint only considers the `_` case:
```rust
// and the second pattern is a `_` wildcard: this is not strictly necessary,
// since the exhaustiveness check will ensure the last one is a catch-all,
// but in some cases, an explicit match is preferred to catch situations
// when an enum is extended, so we don't consider these cases
```

`()` should be fine (I don't think there's any difference between `()` and `{}` for the type checker, and the following works:
```rust
 fn main() {
    let a: () = if let Some(1) = Some(2) {
        ;
    };
}
```

I have not even considered how to do the actual implementation :D But going the text only route will be difficult as well I think, because the new code will need to be reformatted as well. And from glancing at the code, I *think* it should be possible to call `rewrite_if_else()` with the relevant parts of the match without actually having to create new ast nodes, but I'll have to investigate that in more depth.

Also, something I just thought about, maybe we should consider a `#[rustfmt_skip_transform]`, which will only prevent rustfmt from transforming the code (ie. from simple `match` to `if let`) but not from formatting of existing code.

**Comment by nrc** [comment]
Another possible extension would be checking for matches with exactly two arms where one is simple and the other is a wildcard without a predicate and transform these to if let ... else expressions.

**Comment by nrc** [comment]
Hmm, I wonder if we should also transform `=> ()` match arms to `=> {}` - I consider the latter to be better style.

**Comment by nrc** [comment]
Yeah, that seems like good motivation for the wildcard only option.

**Comment by nrc** [comment]
We could add `rustfmt_skip_transform`, I would leave it for later, see if it's useful or not. In particular, at some point Rust should get scoped attributes, and then we can add a load of stuff to the rustfmt:: namespace. But if we add a lot of stuff now, it will be a pain to change it later.
