### ISSUE TITLE
Add an option to rewrite expresssions only if they exceed max_width

### ISSUE THREAD

**Issue by cassiersg** [rust-lang-nursery/rustfmt#346]
See https://github.com/nrc/rustfmt/issues/337#issuecomment-141961422

**Comment by nrc** [comment]
I actually started with this approach (well, and *check* a bunch of stuff too). I find a lot of the benefit of rustfmt comes from things other than just fitting in the line width - e.g., getting whitespace right, nice indenting, uniform punctuation. So, I don't personally think this option would pull its weight. (It's not as simple as it sounds, since once you've found an over-long line, you then need to decide how much to reformat). But if it is really useful and the implementation is not too invasive, then I'd take a patch.

**Comment by Kha** [comment]
To be clear, in #337 I only suggested not re-wrapping lines that are already sufficiently wrapped in the input. I would still expect them to be formatted in all the other ways (which of course may make them exceed max_width, so you'd have auto-wrapping inside of input-specified wrapping. That could be fun).

Also note that this should fix most of the (I suspect) unwanted formatting changes in https://github.com/Manishearth/rust-clippy/pull/343.

**Comment by mkpankov** [comment]
I've also encountered a situation where the option would come in handy:

```diff
@@ -100,11 +100,7 @@ impl_full_ops! {
 
 /// Table of powers of 5 representable in digits. Specifically, the largest {u8, u16, u32} value
 /// that's a power of five, plus the corresponding exponent. Used in `mul_pow5`.
-const SMALL_POW5: [(u64, usize); 3] = [
-    (125, 3),
-    (15625, 6),
-    (1_220_703_125, 13),
-];
+const SMALL_POW5: [(u64, usize); 3] = [(125, 3), (15625, 6), (1_220_703_125, 13)];
 
 macro_rules! define_bignum {
     ($name:ident: type=$ty:ty, n=$n:expr) => (

```
