### ISSUE TITLE
Format macro uses

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#35]
Treat them like method calls. I think this could be tricky because, aiui, we don't parse macro uses. But we can call the parsing code to create an AST, and then we can reformat the body of the use.

**Comment by marcusklaas** [comment]
Is there an other way to build an AST than calling `rustc_driver::run_compiler`? That involves a lot of machinery which seems a bit heavy handed here. It also only takes files as input, AFAIK. So that'd require us to write our snippet to a temp file first...

**Comment by cassiersg** [comment]
I think writing the arg of the macro into a file will not help so much since it's not "standard rust". We can use some heuristics to see if there is a high-level pattern in the arg, and then sub-elements will probably be expressions of statements we can parse, but that's very heuristic. A best solution would be to make the same work as rustc does when it expands a macro.
We have access to the internals of libsyntax, so this should be possible.
After some reading of the code of libsyntax (I'm a total newbie with the internals of rustc, so take what follows with caution), I have found some pointers on how macro expansion works.
The expansion of macro calls is done in `syntax::ext::tt::macro_rules::generic_extension`, with this call of TokenTree::parse)[https://github.com/rust-lang/rust/blob/master/src/libsyntax/ext/tt/macro_rules.rs#L173] that makes the parsing against a macro lhs.
We will thus need to run a phase before this to get all `macro_rules!` compiled, as well as macros from other crates imported. In rustc, this step takes place during the expand phase, where all macros are expanded. We only need to compile `macro_rules!` without expanding macros, so it's a bit tricky...
To make that correctly, we can't only clone the AST, expand it and take the macro defs, since there are issues with lexical scoping. I don't know how to separate macro_rules compiling from macro expanding without a rewrite of some functions of libsyntax, which may quick become big and muddled.

@nrc seems to have worked on this part of rustc, he will probably have better advices.

**Comment by marcusklaas** [comment]
I am afraid we may have different ideas about the scope of this issue. My understanding is that we format macro calls, i.e., `format!("Hello, {}", name)`, as if it was a regular function call. We could do this by replacing the macro name by something without trailing bang and restoring it after the format.

With this understanding, expanding macro's is probably not necessary. Could you elaborate a bit on what goal you had in mind?

**Comment by cassiersg** [comment]
I think we are on the same goal, which doesn't need macro's expanding. However, we need to parse the arg of the macro, `"Hello, {}", name` in your example. This would be simpler if all macros has arg as a list of expressions, but this is not the case.
So we need to be able to distinguish which tokens are part of the "macro's particular syntax" and which form together an expression. (Some cases are not trivial : imagine `macro![X => (Y || Z)]`, where X is an expression, Y and Z statements)
The simplest way to do this is, I think, to use the code of libsyntax that does the _matching+parsing_ part of macro expansion. (and not the expansion itself).
The goal would be to get something like the `named_matches` and `lhs` in [the link of my previous post](https://github.com/rust-lang/rust/blob/master/src/libsyntax/ext/tt/macro_rules.rs#L173) : ASTs corresponding to the tokens of "actual" rust syntax, and not the litterals which are matched by the macro.
I hope it's clear ;)

**Comment by marcusklaas** [comment]
Thanks for your explanation @cassiersg. That makes it a lot clearer for me. You clearly have thought about this a lot deeper than me. I had only considered the simplest case!

**Comment by marcusklaas** [comment]
Closing this as I think we've done this as well as one possibly could.
