### ISSUE TITLE
Unnecessary line split

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang-nursery/rustfmt#415]
```rust
impl Builder {
    fn expr_as_operand(&mut self) {
        debug!("expr_as_operand: category={:?} for={:?}", category, expr.kind);
    }
}
```

turns into

```rust
impl Builder {
    fn expr_as_operand(&mut self) {
        debug!("expr_as_operand: category={:?} for={:?}",
               category,
               expr.kind);
    }
}
```

**Comment by nrc** [comment]
We use a heuristic to split long functions even when not necessary. This is because otherwise rustfmt tends to favour really long functions which are hard to read and people don't tend to write themselves. You can customise it by setting `fn_call_width` to something larger. If you set it to the max-width, it will be ignored. Macros are formatted pretty much like functions.

We could increase the default value, or use a longer value just for macros, or special case macros with string literals (might be worth doing anyway).

**Comment by marcusklaas** [comment]
Closing for now, as this is basically a configuration issue.
