### ISSUE TITLE
Consider putting (slightly longer) struct literals on one line

### ISSUE THREAD

**Issue by rkruppe** [rust-lang-nursery/rustfmt#483]
A variant of #418 for proper structs instead of structvariants, inspired by rust-lang/rust#29113 where the diff contains many slight variations of:

    -            Formatted { sign: sign, parts: &parts[..1] }
    +            Formatted {
    +                sign: sign,
    +                parts: &parts[..1],
    +            }

@marcusklaas assured me that this only happens to "bodies longer than 20 chars", I would prefer if that number was increased (by default - I was told it is configurable). A more complicated heuristic taking the total line length or the number/complexity of the field values into account might also make sense. I can see the benefit of breaking [large, complicated literals][good-ex], but essentially spending four lines of screen real estate on two simple expressions is overkill.

[good-ex]: https://github.com/rust-lang/rust/pull/29113/files#diff-55bd0816ca8c51aa30ecf8304f186124L81

**Comment by nrc** [comment]
I think the example looks better after reformatting. I think we should have struct lits on one line only in really very simple cases (which is why we have the short heuristic length). I imagine we could use a smarter heuristic here, like double the heuristic width if every value is just an ident or something.
