### ISSUE TITLE
Comments in structs converted from `//` to `/* */` 

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#491]
```
-            arm_index: 0, // since we don't call `match_candidates`, this field is unused
+            arm_index: 0, /* since we don't call `match_candidates`, this field is unused */
```

I think we should usually on go the other way, we should only introduce `/* */` when we need to to preserve semantics.

**Comment by marcusklaas** [comment]
The list formatting code formats the comment following the last element of a vertical list in block style when it is not sure the list is immediately followed by a new line.

This is to prevent rustfmt from formatting structs like
```rust
FooStruct { x: 10 /* my fave number */ }
```
as
```rust
FooStruct { x: 10 // my fave number }
```
, since that would break the code.

However, when formatting structs in "block mode", e.g.,
```rust
FooStruct {
    x: 10,
    y: 20, // new line guaranteed!
}
```
this is not necessary.

This can be fixed by properly setting `ends_with_newline` depending on the struct format "style" here: https://github.com/nrc/rustfmt/blob/7e76fad1f55945c196b32e6629ebaecc4ebfda74/src/expr.rs#L1337.
