### ISSUE TITLE
Allow single-line match arm blocks

### ISSUE THREAD

**Issue by wthrowe** [rust-lang-nursery/rustfmt#585]
If a match arm has a really simple block I think it looks better condensed.  ("Really simple" probably means something like single statement, entire arm fits on one line?  Probably something similar to if-else logic.)

```diff
 fn main() {⏎
     match val() {⏎
+        A => {⏎
+            a();⏎
+        }⏎
+        B => {⏎
+            b();⏎
+        }⏎
+        C => {⏎
+            c();⏎
+        }⏎
+        D => {⏎
+            d();⏎
+        }⏎
-        A => { a(); }⏎
-        B => { b(); }⏎
-        C => { c(); }⏎
-        D => { d(); }⏎
     }⏎
 }⏎
```

**Comment by nrc** [comment]
We could have an option for this. I am somewhat conflicted about single line blocks - `if else` makes sense only because it is used like a ternary operator. `unsafe {}` we allow and I think it is worth while, but makes me uneasy, this feels like a step too far - I would generally prefer uniformity over many exceptions which make rare code look better.

Also, I believe this is something of an edge case - if the single item fits on one line and doesn't need a semi-colon, then we put it on one line. It's only if you need a semi-colon to discard the value produced that you need the block.

**Comment by wthrowe** [comment]
Yeah, this may be too rare to be worth handling.  I can certainly understand the argument for avoiding having too many special cases.  (And in fact, in my original case I eventually found a cleaner way to write the code that also happened to change all the expressions to have unit type.)

I'll close this for now, and if anyone feels strongly that this is worth a change they can reopen.
