### ISSUE TITLE
Check that certain options are working

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#609]
Add tests and better documentation where they work, fix things or file issues where they don't work.

```
# Not *entirely* sure how much these do.
where_layout = "Vertical"
where_pred_indent = "Tabbed"

# These don't appear to *do* anything:
chain_base_indent = "Tabbed"
fn_arg_indent = "Tabbed"
ideal_width = 78
```

from https://gist.github.com/DanielKeep/c9ee83dd95ec4ae941c8

**Comment by stepancheg** [comment]
#1305 for `fn_arg_indent`

**Comment by topecongiro** [comment]
What would `wrap_match_arms` do? In [Configurations.md](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#wrap_match_arms), it is described as

>Wrap multiline match arms in blocks

although the given example does not seem to be related to this.

**Comment by nrc** [comment]
I think that description is correct - for a single line match arm, if the option is true it will wrap the arm in a block, even if not necessary, if it is false, then it will only do so if needed for line length reasons

**Comment by topecongiro** [comment]
Thanks for your reply! Although I am still confused...

1. The description states to wrap "multiline" match arms, but the given example is wrapping single-line match arm.
2. Maybe it is just a typo in the example, but the match arm is wrapped in block when `wrap_match_arms` is false.

So the expected behavior is to force using block in match arm when `wrap_match_arms = true`?

**Comment by nrc** [comment]
Hmm, I am also confused, I guess test and see what happens.

1. I think it only applies to single lines, I might be totally wrong though.
2. I think it is a typo, but again I could be wrong.
