### ISSUE TITLE
Use Cargo defaults

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#613]
If we're in a directory with a `Cargo.toml` we could not require a starting file and instead start with `src/lib.rs` or `src/mod.rs` or read the toml file and work out where to start. This would make Rustfmt much nicer to use in a `cargo fmt` style.

**Comment by JanLikar** [comment]
I can do this, but this can get a bit complicated. Do we also format tests, examples, build.rs and benchmarks? To keep it simple I'm planning to check if Cargo.toml is present in the current dir. If it is, format src/main.rs and/or src/lib.rs. This way additional rules can be later implemented. Do you agree?

**Comment by nrc** [comment]
build.rs - maybe, the rest - no. User can use the filename explicitly if they want to format that stuff.

Sounds good. May want to look at src/crate_name.rs and src/bin/crate_name.rs too (note that the latter is a separate crate, so would need to do that and src/lib.rs). Would be good to know if the names can be overridden in the toml file, although you certainly don't need to implement that at first.

**Comment by JanLikar** [comment]
Actually, I changed my mind. If I add the changes we've discussed, it would not be possible to implement a recursive search strategy for `Cargo.toml`, without also preventing usage of stdio mode of the formatter when inside a crate. This change would also be a bit against Unix philosophy, because we would be implicitly searching for a Cargo config file, although rustfmt is not directly tied to Cargo.

I think it would be a much better idea to add `cargo-fmt` binary to this crate, so it could be used as a cargo subcommand `cargo fmt`, don't you think? I believe this would be the best solution.

**Comment by nrc** [comment]
@JanLikar Sure, implementing this for cargo fmt sounds like an excellent idea - I've been meaning to make that work, so this would be great.

**Comment by JanLikar** [comment]
How should I do this? Should I write cargo-fmt separately from https://github.com/pwoolcoc/cargo-fmt or should I contribute to that repository and somehow include it (using git submodules) into this one?

**Comment by nrc** [comment]
You could either implement yourself from scratch or talk to pwoolcoc about merging their code. I don't think it is worth using submodules or anything fancy for this.

**Comment by JanLikar** [comment]
I talked to pwoolcoc and he agrees. I'm getting to work.
