### ISSUE TITLE
Atom does not read the rustfmt.toml config file

### ISSUE THREAD

**Issue by sidred** [rust-lang-nursery/rustfmt#778]
Looking at the atom-beautify source, here is how it works
- copies the source file to a tmp directory ( /tmp on linux)
- runs rustfmt on it
- reads the formatted file
- updates the text in the window if necessary.

This means that the rustfmt.toml in the project root is not read. Not sure what the best way to proceed is:
- overwrite the file in place
  The problem with this is atom does not reload the file automatically
- Use rustfmt display option to manually pipe the output to a destination file. However the display adds additinal informaiton like the filename to the output
- Add a path option for rustfmt to lookup the rustfmt file
- Add a output file option with no added text. 

Any thoughts?

**Comment by nrc** [comment]
There is `WriteMode::Plain` which should do what you want. There is not an explicit option for it. If you use rustfmt in stdin mode (by not specifying any input files), then rustfmt writes in Plain mode to stdout.

If you need to read the file rather than stdout, then you could add a `plain` option to the command line.

**Comment by sidred** [comment]
Which folder does the Write::Plain mode use for the rustfmt.toml? Can you specify it?

**Comment by nrc** [comment]
It looks in the working directory. It would be fine to add a command line option to specify the config file.
