### ISSUE TITLE
Expr formatting : different behavior for last line ?

### ISSUE THREAD

**Issue by cassiersg** [rust-lang-nursery/rustfmt#82]
There are some cases where we want to put some "terminating chars" after an expression, for example `)`, `,` or `}`. If the inner expression is formatted on more than one line, there are two possible behaviors : 
1. Require the room for terminating chars only on last line.
2. Require that the formatted expression has room for the terminating chars on all lines.

In some cases, behavior a. may take more lines, for example : 

```
// behavior 1.
let var_name = Struct {
    a: f1(f2(f3(f4(some + complicated +
                   expression + here)))),
};
// behavior 2.
let var_name = Struct {
    a: f1(f2(f3(f4(some +
                   complicated +
                   expression + here)))),
};
```

I guess it fill not be uncommon to need five of six terminating chars, while having a width budget restricted (we may have `a: x.method1().method2().f1(...`).

Far as I know there is not guidline against behavior 1., so I think it should be used.

Currently, behavior 2. is used (see `rewrite_call` or `rewrite_paren`). To use behavior 1., we would need two width information in `rewrite_*` functions: principal width and last line width.

Any thoughts about that ?

**Comment by nrc** [comment]
I'm confused - I think you invert your use of '1' and '2' between the definitions and examples?

So, I think (but not sure because of the confusion) that we should do what you suggest, i.e., only make room for the extra chars on the last line.

I don't think we need two widths - we can use width for the last line and `config!(max_width) - indent` for the other lines. (This wouldn't quite work - some places we use ideal_width and sometimes max_width, but I would like to use max_width in most places any way, certainly anywhere we're splitting lines like this).

**Comment by cassiersg** [comment]
You're right, the definition numbering was wrong (it's corrected).

The use `config!(max_width) - indent` seems logical in this case.

BTW, where should ideal_width be used ?

**Comment by nrc** [comment]
Reopening, because I think this is something we should fix.

I'm not quite sure where we should use ideal vs max width to be honest. Comments should definitely use ideal_width and expressions should definitely use max_width. I'm not too sure about the rest. I had thought that items which wrap over many lines (e.g., multi-line string literals and `use` imports) should use ideal_width, but this looks a bit odd to my eye. Perhaps items should all use ideal_width? Another way to use them is to use max_width if we can fit everything on one line, but ideal_width once we start breaking. I felt this looks odd for imports at least, it might work with expressions and function defs.
