### ISSUE TITLE
Long doc comment lines cause failure

### ISSUE THREAD

**Issue by matthewkmayer** [rust-lang-nursery/rustfmt#822]
```bash
rustfmt --version
0.3.0
```

As seen when running `rustfmt`:

```bash
rustfmt src/credentials.rs 
Rustfmt failed at src/credentials.rs:7: line exceeded maximum length (sorry)
```

First line in question:
https://github.com/rusoto/rusoto/blob/master/src/credentials.rs#L7 which is 106 chars:

`//! 3. IAM instance profile.  Will only work if running on an EC2 instance with an instance profile/role.`

Also fails on other long doc comment lines (https://github.com/rusoto/rusoto/blob/master/src/credentials.rs#L27):

`/// Represents AWS credentials.  Includes access key, secret key, token (for IAM profiles) and expiration timestamp.`

**Comment by nrc** [comment]
You can use `wrap_comments` to format comments including doc comments into the max line width. The trouble is, it doesn't work very well, which is why it is off by default.

**Comment by nrc** [comment]
Sorry, to be clear, `wrap_comments` is a config option you can set.

**Comment by neandrake** [comment]
I just came across this as well and found rustfmt's output confusing. Is this an error which is intended to be fixed? From your comments it sounds like this is expected behavior but rustfmt's output makes me believe it failed parsing my source file. Should the error line be rephrased or removed altogether?
