### ISSUE TITLE
How to know which rule is changing my code

### ISSUE THREAD

**Issue by calebmer** [rust-lang-nursery/rustfmt#832]
How can I tell which rule to change when my code gets mangled in a way I don't want it to be. This is a general question, but a specific block of code I have been struggling with is this using the clap dsl:

```rust
let matches = {
  App::new("app")
  .version(crate_version!())
  .settings(&[
    AppSettings::GlobalVersion,
    AppSettings::VersionlessSubcommands,
    AppSettings::UnifiedHelpMessage,
    AppSettings::ArgRequiredElseHelp
  ])
  .args(&[
    Arg::with_name("url").takes_value(true).required(true),
    Arg::with_name("yes").long("yes").short("y")
  ])
  .subcommands(vec![
    SubCommand::with_name("ls").arg(Arg::with_name("verbose").short("v")),
    SubCommand::with_name("create").arg(Arg::with_name("name").takes_value(true).required(true))
  ])
  .get_matches()
};
```

Becomes:

```rust
let matches = {
  App::new("app")
  .version(crate_version!())
  .settings(&[AppSettings::GlobalVersion, AppSettings::VersionlessSubcommands, AppSettings::UnifiedHelpMessage, AppSettings::ArgRequiredElseHelp])
  .args(&[Arg::with_name("url").takes_value(true).required(true), Arg::with_name("yes").long("yes").short("y")])
  .subcommands(vec![SubCommand::with_name("ls").arg(Arg::with_name("verbose").short("v")),
                    SubCommand::with_name("create").arg(Arg::with_name("name").takes_value(true).required(true))])
  .get_matches()
};
```

The original version is desired.

**Comment by nrc** [comment]
There's not really a way to solve this with the current implementation of rustfmt. The tool operates in a mode where it parses the text to AST then rewrites the AST, it doesn't check and correct the original text. There is no concept of 'rules' for writing the AST, just an algorithm for doing so.

One could imagine a refactoring (more like a rewrite) where rules for rewriting were made explicit.

The tool could also tell you which config options were used to format a given piece of text. That would actually be possible to implement in a reasonable amount of time, and would be fun to do. Not sure that it would solve your problem though (unless the config options get fine-grained enough to represent a single rule).

Closing for now, since I don't think there is a possible solution. But if the config options thing sounds useful, we can open an issue for that.

**Comment by calebmer** [comment]
Yes, that config transparency option would be very nice.
