### ISSUE TITLE
Determine if rustfmt found issues

### ISSUE THREAD

**Issue by MasonRemaley** [rust-lang-nursery/rustfmt#853]
Is there currently a way to programmatically determine if rustfmt detected any issues? This would be helpful if you wanted to (for example) set up a git hook that denies commits with formatting issues.

**Comment by nrc** [comment]
The best way is to diff before and after running rustfmt (or run in 'diff' mode and check to see if the output is empty). Obvs, that is not ideal.

We could use some kind of error code for this. ATM, we return an error code if formatting did not succeed and success if it did. We could have a check mode which works like diff mode (not writing to files) and just returns success or failure rather than a diff.

**Comment by nrc** [comment]
See also #860.

**Comment by MasonRemaley** [comment]
That'd be perfect, the first thing I checked when trying to figure out if this was already supported was whether or not any of the write modes had this behavior.

**Comment by nrc** [comment]
This should be address by #923

**Comment by MasonRemaley** [comment]
Finally got back around to what I was doing when I asked this--works great now!
