### ISSUE TITLE
Don't extend line lengths beyond "ideal width"

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustfmt#861]
I personally prefer 80 character code wherever possible, so I will tend to wrap lines to 80 characters when writing. I believe that rustfmt also has the concept of "ideal width" vs "maximum width", where the ideal by default is 80.

There's code, however, which rustfmt will reformat to *greater than 80 characters* if it's already under 80, for example:

```rust
fn foo() {                                                                      
    match foo {                                                                 
        bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb => {
            24242                                                               
        }                                                                       
    }                                                                           
}                                                                               
```

The number will be moved to the same line as the match expression when run through rustfmt.

Would it be possible to not extend code beyond the ideal limit?

**Comment by nrc** [comment]
The ideal width is only used for text - comments and string literals, iirc. Rustfmt doesn't really have a concept of leaving code alone if it passes some tests and reformatting otherwise - it just writes out everything (well, some string lits/comments it can leave alone, but not regular AST stuff). So, atm, it isn't possible to do this.

Initially I tried to wrap code to the ideal limit and occasionally go into the max, but this turned out to be weird and I abandoned it pretty early on. I think if you want 80 char lines, you have to set the max to 80. We might be able to experiment with some other uses for ideal/max width, but I don't have any concrete ideas at the moment.

**Comment by nrc** [comment]
Closing this issue because I don't think it is actionable in the foreseeable future (although I agree it is desirable).
