### ISSUE TITLE
What is the best way to use rustfmt from within IDE?

### ISSUE THREAD

**Issue by matklad** [rust-lang-nursery/rustfmt#876]
Hi! 

I'd like to integrate `rustfmt` with intelliJ Rust ([PR](https://github.com/intellij-rust/intellij-rust/pull/289)). However I am not sure how to do this properly, because the most obvious solution of calling `cargo fmt -- --write-mode overwrite --skip-children $filePath` had several surprises :) 

* I want to reformat only one file, but `cargo fmt` [unconditionally adds](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/bin/cargo-fmt.rs#L72-L80) `lib` and `bin` crate roots.

* It [requires](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/bin/cargo-fmt.rs#L177) `rustfmt` to be present in PATH and does not look into $CARGO_HOME/bin, which plays badly with multirust. 

* It happily returns `0` exit status, even if everything has gone wrong :)

Does this mean that I'm better of calling `rustfmt` directly? I'd rather avoid this and call only `cargo` commands from the IDE.

**Comment by nrc** [comment]
I think calling rustfmt is probably a better idea than using cargo fmt. cargo fmt is designed to be easy to use in the typical case, but not as general. Whereas, it sounds like you want to do quite specific things with rustfmt. In fact, I might go so far as making my own executable using rustfmt as a library, rather than using the rustfmt executable (but hopefully you won't have to go that far).

To address the points specifically:
* I think using rustfmt directly is the best solution to this. If you are really keen to only use cargo, we could take a patch to address this (add a command line argument, should be quite simple).
* I'd be happy to have this fixed, I'm not exactly sure what the Cargo defaults are that we should use, but working with multirust would be a great benefit. Maybe best to check with #cargo, that we do the right thing here.
* Definitely would be good to fix this.

**Comment by matklad** [comment]
>I think using rustfmt directly is the best solution to this.

I agree. The only thing left is to find out, how to launch `rustfmt` without relying on it being in `PATH`. Basically, I need `cargo execute-binary-I-have-just-installed-with-cargo-install rustfmt`. Asked about it on IRC.

**Comment by nrc** [comment]
cc @alexcrichton in case he has some input from the Cargo angle.

**Comment by alexcrichton** [comment]
Sounds like there's agreement on calling `rustfmt` directly for one file situations (which seems reasonable to me as well), and for finding `rustfmt` that seems surprising because how is `cargo` being found? In a rustup world everything its actually in `$CARGO_HOME/bin` (including `cargo`) so if one is in your path then both are.

That being said, we could add something like `cargo install --print-root`. Ideally it'd be `cargo config install.root`, but that can perhaps come later :)

**Comment by matklad** [comment]
> that seems surprising because how is cargo being found?

Ah, sorry, I've forgot to mention that we call cargo using the absolute path (which is basically specified by user).

**Comment by alexcrichton** [comment]
Ah yeah I guess that'd do it :(

**Comment by matklad** [comment]
@alexcrichton actually I think there may be pretty legitimate reasons to have `cargo` in PATH, but not `~/.cargo/bin/` (for example, if you install rust via an operating system package manager). I will think about what I need here exactly and open an issue in the cargo repository. 

`cargo install --print-root` is one possible solution, `cargo execute-binary-I-have-just-installed-with-cargo-install` is another one.

**Comment by alexcrichton** [comment]
Hm that's somewhat at odds with the rustup design that @brson is working on (cc to this thread as well). The assumption is that cargo-installed tools are indeed in PATH so other tools (like IDEs) can benefit

**Comment by brson** [comment]
I suggest ides look in ~/.cargo/bin for rustmft, regardless of how cargo is found. This directory is easy for all rust tools to find, and it's where any cargo will put rustfmt. It's the only thing rustup really knows about cargo.

Note that there's a bug in how cargo find this for today on Windows.

**Comment by matklad** [comment]
>I suggest ides look in ~/.cargo/bin for rustmft, regardless of how cargo is found.

So tools should not assume that PATH is set up properly? And in particular, [this line](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/bin/cargo-fmt.rs#L177) in cargo-fmt should ideally be change to look for `rust-fmt` in `~/.cargo/bin`, shouldn't it? 

>Note that there's a bug in how cargo find this for today on Windows.

The windows story is actually the most interesting one, because it is often a bit harder and receives less testing :(

What is the alternative of `~/.cargo/bin` on windows? Is it `.cargo/bin` in `%USERPROFILE%`?

**Comment by alexcrichton** [comment]
In theory for tools to be the "most robust" they'd want to handle not being in `$PATH`, but we may also not want to duplicate the logic everywhere :). I do believe that on Windows the home directory is in `%USERPROFILE%` (or something similar)

**Comment by matklad** [comment]
> I do believe that on Windows the home directory is in %USERPROFILE% (or something similar)

Hm, looks like it may be either in %USERPROFILE% or in `AppData\Local`. In the ideal world, it should be possible to change the location of this directory (and adapt XDG conventions without any breakage, for example), but we are not in the ideal world yet :) 

So for now I will just try to search for `rustfmt` in several different locations. @alexcrichton if you decide that cargo needs `--print-root` or something like `python -m` I'd be happy to contribute :)

Thanks for the feedback!
