### ISSUE TITLE
Option to preserve indent in empty lines.

### ISSUE THREAD

**Issue by kevincox** [rust-lang-nursery/rustfmt#887]
Hello, it would be nice to have the option to put whitespace on empty lines to match the current indent level.

``` rust
fn foo() {
   let thing = 1;
   <- Keep this indent.
   let thing = 2;
}
```

**Comment by sbstp** [comment]
Is there a particular reason why you want this? Keeping whitespace on empty lines can create really messy diffs. A lot of editors already trim lines too.

**Comment by kevincox** [comment]
It is personal preference like most formatting settings. I like being able to easily position my cursor on an empty line and also have my editor configured to display indentation so that I can easily follow the levels. 

Also I don't see why the diffs would be messy. And if editors trim the lines that's what a formatter is for :)

**Comment by daboross** [comment]
One reason editors and tools almost universally strip whitespace off of the empty lines is in cases between two lines with different indents, it may be hard to judge which indent to take, and that could lead to unnecessary diff changes in commits with different editors/tools, as well as confusion when editing the library. Example:

```rust
fn function() {
    {
        inner_function_call();
// how much indent here,  8 spaces or 4?
    }

    really_long_method_call(inner_argument_1, inner_argument_2, inner_argument_3,
            inner_argument_4, inner_argument_5);
// how about here? 12, 4, or 0?
}
```

This is also somewhat related to the standard of removing all whitespaces from the end of lines (e.g. changing `...;<whitespace here>` to `...;`).

The diff thing is somewhat related as well: in general, there are few tools which will specifically *format* whitespace on empty lines to a specific length, so all whitespace on empty lines which ends up being committed to repositories is purely because of someone forgetting to remove it - this leads to an inconsistent amount of whitespace on different lines, and if no one updates it, or if different tools update it differently, it can end up adding completely unrelated lines to a `git diff` or patch file.

This is somewhat similar to the issue of mixing tabs/spaces in a repository: if the only person who updates it updates it inconsistently, or if some editors format with spaces and others with tabs, many, many unnecessary changes can be added to a patch file leading to merging hell. The solution being to agree on one standard: spaces for indentation, or in this case almost universally, no whitespace after the last non-whitespace character on a line. Straying from the standard is OK, but it usually has more downsides than upsides. For example, if someone is trying to contribute to your project, and if they're editor is configured, as many are, to immediately remove all end-of-line whitespace, they'll have to either manually re-add all of the whitespace, change their editor setting, or, more likely, submit a pull request with many more lines changed than would otherwise have been required.

If you like being able to keep your cursor position constant when scrolling, many editors I've seen do have the option to allow caret placement past the end of the line, allowing it to seem like there's whitespace there without actually saving any. Also, I'm only really trying to criticize the choice you've made a little bit - you are completely free to choose to have whitespace on empty lines. I'm just trying to provide some of the reasoning behind not allowing it, and why it probably isn't the highest priority to add to rustfmt (I wouldn't know about this, as I am not a contributor, but just guessing).

**Comment by kevincox** [comment]
@daboross I see your point about where the indent should lie. But unlike python I think the answer is usually quite clear in rust.

```rust
fn function() {
    {
        inner_function_call();
        // It is inside the scope so 2 levels of indent.
    }

    really_long_method_call(inner_argument_1, inner_argument_2, inner_argument_3,
            inner_argument_4, inner_argument_5);
    // It is outside of the argument list, but inside the outer scope so 1 level.
}
```

In all cases I can think of the indent could be sanely, and consistently defined.

**Comment by daboross** [comment]
That is true, and I guess my post isn't really an argument *against* including this in rustfmt - mostly a reason for why it isn't done in general or why it hasn't already happened.

I guess the only reason for not including it would be the confusing factor for people who would be possible contributors to projects with a 'add-whitespace' setting enabled. Most programming editors I know remove whitespace at the end of lines / on empty lines by default, so this would just cause a small change submitted by someone possibly turning into them attempting to commit a large style change without realizing it.

The only other thing is having whitespace at the end of a line is usually warned against in command line versions of git and other tools, and specifically it would/will make using `git merge` and `git diff` more complicated. Git uses empty lines to separate changes, so it will just be more work merging branches with such a setting enabled.

The two above things are mostly what people meant by `messy diffs` I believe.

**Comment by chylex** [comment]
Unfortunately some of the most common IDEs and editors (IntelliJ, VS Code) don't work well at all when indents are stripped from empty lines. It makes navigation so confusing when the cursor constantly jumps left and right, and typing on empty lines requires additional reformatting which is very annoying.

Sadly that's a blocker for me, I cannot use rustfmt or accept PRs that use rustfmt if they keep messing up indents and making navigating and writing code more difficult.

**Comment by Waridley** [comment]
Frankly I don't understand why this issue is closed as if it won't be fixed, instead of allowing potential PR's if someone wants to implement it.

We're not trying to argue about which way is correct or should be the default (of course the default should stay exactly what it is now even if the alternative were "better" just so it doesn't break anything). We're just trying to allow users to make the decision for their own code. They can have the argument in their own repositories if they want to change the default.

**Comment by TheTechn0mancer** [comment]
This should be reopened. Removing whitespace from empty lines actually affects my productivity. I shouldn't have to manually indent lines just because I want to add code to a previously blank line. The indentation of a code block should be extremely concrete and solid. Washing away indentations is against the very idea of a code block being indented. Again, I hate that adding a blank line and saving (which triggers a format) causes the indentation to be erased, meaning that I have to manually tab it out when I go to  add more code to the program. I like code to be formatted as I type. Removing indentations is not any kind of formatting whatsoever. Removing superfluous indentation, fixing line endings, and such is a job for an entirely different step of the toolchain, and ONLY comes into play when committing source code. It should never even happen to the local file.

**Comment by kaya3** [comment]
Adding my voice to those who want to see this as an option. This is the main reason I don't use rustfmt myself.

But also, someone else mentioned "messy diffs" as a reason not to have it, and I think that is backwards. In my case, somebody contributed code to one of my projects and inadvertently removed all of the whitespace from the empty lines, creating a diff which was mostly whitespace ─ and I had to merge their contribution manually so as not to merge in the whitespace changes, which I did not want.

It's OK to say that I don't have to use rustfmt if I don't like it, but here it's getting in the way of me accepting contributions from other people who do use it. If this was configurable then I could put it in the project's config file and there would be no problem. I hope that the answer is not that I just have to accept this from other people using rustfmt if I want to accept their contributions, because as other people have mentioned, this is a usability issue, not a stylistic preference.

**Comment by calebcartwright** [comment]
@kaya3 if you don't want to use rustfmt in your project(s) and you don't want contributors running rustfmt (intentionally or unintentionally) then the standard response applies:

add a `rustfmt.toml` file to your project, and set the [disable_all_formatting](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=disable#disable_all_formatting) option to `true`

**Comment by Clonkex** [comment]
This is crazy. Why would any formatting tool _remove_ indentation from empty lines? It should be indented whether it has code or not. Otherwise it's just painful every time I want to add code to a blank line. No other tool does this, so why does rustfmt do it? Or more to the point, why is it not an option? It's not trailing whitespace (except in the pedantic sense) so why is it being removed?

> or in this case almost universally, no whitespace after the last non-whitespace character on a line
This is simply not true. I've been programming professionally for 8 years and have used many editors and not a single one removed empty line indentation by default. Obviously no one wants whitespace after the last non-whitespace character on a line containing code, but the indentation should always exist!

Can this please be reopened?

**Comment by LikeLakers2** [comment]
I apologize, but I have to be blunt to the rustfmt maintainers here.

It's been two years and some change since I made my comments here, asking for this sort of thing. I'm still surprised there's not an inch of progress towards this, especially in the face of so many asking for it.

I get that rustfmt is a code formatter, and an opinionated one at that. I'm not going to say that I can't expect some concessions to be made, and I understand if implementation of this goes rather slow (as things in the rust repositories often seem to do). But it still baffles me that our feelings on this matter are... for lack of a better way to put it, being deliberately and entirely ignored.

It just... upsets me every time I see this issue in my notifications. Every time someone comments here, it's a reminder of how little our words actually seem to matter if none of the maintainers care. It's a reminder of how good rustfmt could have been for so many developers, and yet it isn't.

**Comment by calebcartwright** [comment]
I'm going to lock this because the matter was resolved a long time ago. To reiterate the team's position that's been stated a few times:

This is not something the rustfmt team is going to work on.

There's plenty of other features, some desired by a much greater number of people than this one, which we're not going to work on ourselves either. We're not going to work on it because (1) it's not part of our core focus area (being the implementing tool for Rust's official [Style Guide](https://doc.rust-lang.org/nightly/style-guide/)) and (2) we know what a complex implementation effort this would require, we have other higher priorities and don't have the time for this custom feature.

This is an open source project at the end of the day. For those that disagree and think that this custom feature would be easy to implement and reasonable for our team to maintain and support, please feel free to make an attempt to develop it and submit a Pull Request. We wouldn't reject such a PR just for the sake of it, we're simply stating the team's position that it's an infeasible ask of us and our belief that an implementation is impractical based on experience, priorities, and bandwidth.

If you want to see this, then try to implement it. However, attempts to guilt and shame a couple of volunteer maintainers that spend some of their free time on nights and weekends trying to maintain and advance a tool, simply because they wouldn't implement a custom feature you wanted, is not going to be effective and it will not achieve your desired outcome.
