### ISSUE TITLE
bad format when use --write-mode=display (or coverage), it included the mods directly into the being formated code.

### ISSUE THREAD

**Issue by liuchong** [rust-lang-nursery/rustfmt#939]
rustfmt --version
0.4.1

before format:
``` rust
// main.rs
mod mod1;
mod mod2;

fn main() {
    mod1::test();
    mod2::test();
}

// mod1.rs
pub fn test() {
    println!("test in mod1");
}

// mod2.rs
pub fn test() {
    println!("test in mod2");
}
```

after format:
``` rust
main.rs:

mod mod1;
mod mod2;

fn main() {
    mod1::test();
    mod2::test();
}
mod1.rs:

pub fn test() {
    println!("test in mod1");
}
mod2.rs:

pub fn test() {
    println!("test in mod2");
}
```
In emacs buffer it will be:
``` rust

mod mod1;
mod mod2;

fn main() {
    mod1::test();
    mod2::test();
}

pub fn test() {
    println!("test in mod1");
}

pub fn test() {
    println!("test in mod2");
}
```

which I've found is that, when use "rustfmt main.rs" as default, it will be all right; but when use "rustfmt --write-mode=display main.rs", it will be the wrong output as above show.

Is it a bug or should be something wrong of my environment?

Thanks!

**Comment by nrc** [comment]
This is kind of a feature, not a bug :-) When you use write-mode display, it works on all the modules (just like other write modes) and dumps all the output to the console. Other modes would dump output into the submodules' files. We used to output the filename for each file as we dumped it to the console, but it looks like we stopped doing that, I don't remember why.

I wonder if we should start again if there is more than one file?

**Comment by liuchong** [comment]
I'm using emacs, it seems the rust-format-buffer using a "write-mode display", after type C-c C-f, it loaded all the mod into current buffer, strange.

**Comment by liuchong** [comment]
@nrc In fact it will still output the filename for each file, I've copied the code from emacs buffer, let me modify it.
so, it's a emacs rust-mode issue, not rustfmt?

**Comment by nrc** [comment]
Hmm, it does seem like a rustfmt/emacs issue rather than a pure rustfmt thing. I'm not sure how rustfmt/emacs works though, so I'm not really sure what is happening. I suppose it shouldn't be using the display mode? There are a few issues filed already for things like formatting just given lines or a module but not its sub-module which should help here.

**Comment by MicahChalmer** [comment]
When the source is given to rustfmt as input rather than as a file name, no filenames are printed, but the contents fo the modules are still included--at the root level, as if they were in the current module.  For instance, if I have foo.rs:
````rust
mod bar;
mod baz;

fn function_from_foo() {}
````

bar.rs:
````rust
fn function_from_bar() {
}
````

baz.rs:
````rust
fn function_from_baz() {
}
````

If I invoke `rustfmt --write-mode=display foo.rs` I get the following output, which is correct as per the discussion above:

````text
bar.rs:

fn function_from_bar() {}
foo.rs:

mod bar;
mod baz;

fn function_from_foo() {}
baz.rs:

fn function_from_baz() {}
````

However, if I do `rustfmt < foo.rs` (which is more or less equivalent to what the emacs mode is doing) I get something like this output, which I don't think is useful for any purpose:

````text
fn function_from_baz() {}
fn function_from_bar() {}
mod bar;
mod baz;

fn function_from_foo() {}
````

It has simply concatenated the modules together, without giving any file names or indication of where they begin or end.

Both the incorrect mode (when reading from stdin) and the correct mode (from the file) seem to output the files in a non-deterministic order--sometimes the submodules are first, sometimes last, sometimes one first and the other last.

An earlier version of rustfmt (v0.2.1) used to not output the submodules at all when invoked with code from stdin rather than from a file.  The latest version (v0.4.1 as of this writing) has the bad behavior described here.

I think the earlier behavior should be restored.  If not, at the very least the filenames should be there, and there should be an option not to output the modules from other files (nor should it even need to parse them in that case.)

**Comment by MicahChalmer** [comment]
Ok so it looks like the `--skip-children` flag already exists that tells it not to print submodules...but it only works when running against a file specified with a path.  It doesn't do anything when running from stdin!  I would consider that a bug (and the fix looks fairly simple...I'll send a PR for it.)

**Comment by liuchong** [comment]
Tried in emacs and it working well now, thanks!
