### ISSUE TITLE
Survey for Code Style Preferences

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rustfmt#962]
Recently I saw CSScomb's ["Build your own config"](http://csscomb.com/config) page, which allows users to choose their favorite code style by choosing from examples multiple times (I think the examples even built upon previous choices).

Do you think this is something we could/should do for rustfmt as well?

This could also be used to find the code style that most people prefer.

**Comment by nrc** [comment]
This would be awesome for rustfmt to have! It would be a great way to demo rustfmt on a webpage too.

I don't actually think this would be easy - it would be a big job - but you wouldn't need to know anything about rustfmt internals.

**Comment by sgrif** [comment]
Maybe easy is the wrong label then? ;)

**Comment by nrc** [comment]
> Maybe easy is the wrong label then? ;)

My thought process is that it is an appropriate issue for someone new to rustfmt to work on, but that is rather verbose for a label :-)

**Comment by killercup** [comment]
"Easy" aside, I like the "Fun!" label!

I would absolutely help out getting the web part going, so that we 'only' have to gather enough style options/examples 😄

**Comment by sgrif** [comment]
I'm happy to help as well

**Comment by cramertj** [comment]
I'd also be interested in helping.

**Comment by justgage** [comment]
This would be used to find a default for rustfmt right? Rather than helping people build configs. I feel like there should be at least a little friction to building configs so that only the people that do it are the really opinionated people.

**Comment by mikr** [comment]
When you already have Rust sources with an undefined style that you like to adopt with rustfmt, you can use [whatstyle](https://github.com/mikr/whatstyle) to find the most similar rustfmt option values.

Furthermore by running, e.g.: `whatstyle.py --variants yoursource.rs` you can see how changing the option values would affect your code and eventually modify the style accordingly.

Maybe this is an alternative to "Build your own config" for you.

**Comment by m-decoster** [comment]
I have begun to implement something like this: https://github.com/m-decoster/rustfmt-cfg-generator.

It is far from complete but I am planning on adding configuration options over time. I would also like to eventually run this on a web server and have a page where you can try out your generated configuration file by copy-pasting code.

If you wish to contribute to this or have any remarks, feel free to do so.

**Comment by mikr** [comment]
Hello Mathieu,

this looks interesting, here are some things that I noticed for your consideration.

1)
After seeing the first two options I was wondering why you are not showing the resulting differences
between the options as you do starting with option 3.
To give a stronger first impression consider placing the diffless options after those that show diffs.
Even the options that only influence rustfmt console output (fixme/todo) could be shown as
shell output side by side.

2)
A back button would be useful.

3)
The intermediary rustfmt config file could be shown at each step eventually with the current option
highlighted separately while showing all available option values.

4)
I think good defaults are useful. If rustfmt has a default style consider putting the default option
always on the left side and make this clear to the user. If the user doesn't care about an option one way
or the other he is probably best served by sticking to the default.

Greetings,

Michael

**Comment by m-decoster** [comment]
1)
For those first two options, it's because I haven't found a good clear example yet. I do think your point about diffless options showing after those with diffs is useful. I'll also add the shell output diffs, great idea.

2)
You're right, I will implement this.

3)
The intermediary rustfmt config file could be shown at each step eventually with the current option
highlighted separately while showing all available option values.

Very good idea.

4)
I think good defaults are useful. If rustfmt has a default style consider putting the default option
always on the left side and make this clear to the user. If the user doesn't care about an option one way
or the other he is probably best served by sticking to the default.

This is already implemented actually: a checkmark indicates the default, an x mark indicates non-default options. The default is always on the left. I should make this more clear if it wasn't immediately obvious.

I also share @justgage's concerns that easy config generation could cause people to stray from the "default" Rust style too much. This is certainly something to consider.

**Comment by nrc** [comment]
cc @rust-lang-nursery/style

**Comment by ubsan** [comment]
I think it's interesting, but the issue is that rustfmt doesn't implement the major issues; I still don't think it's possible to use block indent everywhere with rustfmt. I could see it being useful as a survey if it went into these kinds of things that rustfmt doesn't yet implement.
